-- =====================================================================================
--  THE CHAMPIONS CLUB  -  Sports Club Management System
--  Database schema  |  PostgreSQL 14+  |  run top to bottom on an empty database
-- =====================================================================================
--
--  ROLES (decided)
--    1 owner        2 manager (exactly ONE)   3 front_desk (also handles enquiries)
--    4 shop_staff   5 bar_staff (bar, cafe, kitchen)   6 accountant
--    7 member (Gold / Silver / Junior are PLANS, not roles)   8 system_admin
--
--  SECTIONS
--    1  Identity & access     roles, permissions, role_permissions, users, user_roles
--    2  Club profile/settings club_profile, club_settings
--    3  Staff (HR)            employees, shift_templates, shifts, attendance_records,
--                             leave_types, leave_requests, payroll_runs, payroll_items
--    4  Members & customers   guardians, membership_plans, plan_benefits, members,
--                             memberships, guests, business_clients, member_notes
--    5  Courts & bookings     sports, courts, court_operating_hours, court_rates,
--                             court_reservations, bookings, check_ins
--    6  Tax                   tax_rates
--    7  Gear shop & stock     product_categories, products, product_variants, suppliers,
--                             purchase_orders, purchase_order_items, stock_movements,
--                             shop_orders, shop_order_items
--    8  Bar & cafeteria       bar_menu_categories, bar_menu_items, dining_tables,
--                             bar_tabs, bar_orders, bar_order_items
--    9  Enquiries (CRM)       enquiries, enquiry_activities, quotes, quote_items
--    10 Finance               invoices, invoice_items, payments, refunds, daily_closings,
--                             expense_categories, expenses, tax_returns, report_shares
--    11 Notifications & audit notifications, audit_logs
--    12-15 Triggers, indexes, seed data, reporting views, availability function
--
--  CONVENTIONS
--    * ids are bigint identity. Money is numeric(12,2). Percentages are numeric(5,2) (0-100).
--    * text + CHECK (...) is used instead of ENUM so allowed values are easy to edit.
--    * Unit prices are tax-EXCLUSIVE. invoice/order line_total = qty*unit_price - discount + tax.
--    * Snapshot columns (price, discount %, rate used) are copied at the time of sale so
--      later plan or price changes never rewrite history.
--    * day_of_week: 0 = Sunday ... 6 = Saturday (same as PostgreSQL EXTRACT(DOW)).
--    * Numbers such as invoice_no / order_no / booking_ref / member_code are generated by
--      the application; the database only guarantees they are unique.
--
--  KEY GUARANTEES ENFORCED BY THE DATABASE (not just the app)
--    * Two bookings can never overlap on the same court  (exclusion constraint, section 5)
--    * Max N bookings per member per day (default 2)     (trigger, setting in club_settings)
--    * Social-play sessions cannot exceed their capacity (trigger)
--    * Shop stock can never go negative; counter and online sales hit the same stock row
--    * Exactly one owner and one manager                 (unique indexes, section 1)
--    * A member cannot hold two overlapping memberships  (exclusion constraint, section 4)
--    * invoice.amount_paid / status follow the payments  (trigger, section 10)
--    * A payment can never be refunded for more than it was (trigger, section 10)
--
--  ASSUMPTIONS TO CONFIRM  (search for "ASSUMPTION" in this file)
--    A1 Juniors (under 18) need a guardian record.
--    A2 Both exclusive and social-play bookings count toward the 2-per-day limit.
--    A3 Prices are tax-exclusive; tax rates are GST-style placeholders.
--    A4 Currency INR, timezone Asia/Kolkata (UPI is mentioned in the statement).
--    A5 Sports list contains tennis, padel, badminton AND cricket because the problem
--       statement mentions both sets - keep only what the club offers.
-- =====================================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- needed for the "no overlap" exclusion constraints

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END $$ LANGUAGE plpgsql;


-- =====================================================================================
-- 1. IDENTITY & ACCESS
-- =====================================================================================

CREATE TABLE roles (
    id          smallint PRIMARY KEY,                 -- fixed ids, see seed data (section 14)
    code        text NOT NULL UNIQUE,
    name        text NOT NULL,
    description text
);

CREATE TABLE permissions (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code        text NOT NULL UNIQUE,                 -- 'module.action', e.g. 'booking.manage'
    module      text NOT NULL,
    description text
);

CREATE TABLE role_permissions (
    role_id       smallint NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    permission_id bigint   NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- One login account per person: staff AND members who use the website/app.
CREATE TABLE users (
    id                   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name            text NOT NULL,
    email                text,
    phone                text,
    password_hash        text NOT NULL,
    status               text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','disabled')),
    must_change_password boolean NOT NULL DEFAULT false,
    failed_login_count   smallint NOT NULL DEFAULT 0,
    locked_until         timestamptz,
    last_login_at        timestamptz,
    email_verified_at    timestamptz,
    phone_verified_at    timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_contact_chk CHECK (email IS NOT NULL OR phone IS NOT NULL)
);
CREATE UNIQUE INDEX uq_users_email ON users (lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX uq_users_phone ON users (phone)        WHERE phone IS NOT NULL;

-- A user can hold more than one role (e.g. front_desk + accountant in a small club).
CREATE TABLE user_roles (
    user_id     bigint   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id     smallint NOT NULL REFERENCES roles(id),
    assigned_by bigint   REFERENCES users(id),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
-- Exactly one owner and exactly one manager (role ids 1 and 2).
-- To allow several managers later, just DROP INDEX uq_single_manager;
CREATE UNIQUE INDEX uq_single_owner   ON user_roles ((true)) WHERE role_id = 1;
CREATE UNIQUE INDEX uq_single_manager ON user_roles ((true)) WHERE role_id = 2;


-- =====================================================================================
-- 2. CLUB PROFILE & SETTINGS   (feeds the public website and the booking rules)
-- =====================================================================================

CREATE TABLE club_profile (                           -- always exactly one row
    id            smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    name          text NOT NULL,
    tagline       text,
    description   text,
    address_line1 text,
    address_line2 text,
    city          text,
    state         text,
    postal_code   text,
    country       text NOT NULL DEFAULT 'IN',
    latitude      numeric(9,6),                        -- "find a place to play near me"
    longitude     numeric(9,6),
    phone         text,
    email         text,
    website_url   text,
    logo_url      text,
    tax_id        text,                                -- GSTIN / VAT number printed on invoices
    currency_code char(3) NOT NULL DEFAULT 'INR',      -- ASSUMPTION A4
    timezone      text NOT NULL DEFAULT 'Asia/Kolkata',
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE club_settings (                          -- business rules the admin can change
    key         text PRIMARY KEY,
    value       text NOT NULL,
    description text,
    updated_by  bigint REFERENCES users(id),
    updated_at  timestamptz NOT NULL DEFAULT now()
);


-- =====================================================================================
-- 3. STAFF (HR): employees, shifts, attendance, leave, payroll
-- =====================================================================================

CREATE TABLE employees (
    id                     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_code          text NOT NULL UNIQUE,
    user_id                bigint UNIQUE REFERENCES users(id),   -- their login (NULL if none)
    full_name              text NOT NULL,
    phone                  text NOT NULL,
    email                  text,
    date_of_birth          date,
    address                text,
    emergency_contact_name  text,
    emergency_contact_phone text,
    department             text NOT NULL CHECK (department IN
                              ('management','front_desk','shop','bar','kitchen','finance','admin')),
    job_title              text NOT NULL,
    employment_type        text NOT NULL DEFAULT 'full_time'
                              CHECK (employment_type IN ('full_time','part_time','casual')),
    hire_date              date NOT NULL,
    termination_date       date,
    status                 text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','terminated')),
    reports_to_employee_id bigint REFERENCES employees(id),      -- leave/shift approver (the manager)
    pay_type               text NOT NULL DEFAULT 'monthly' CHECK (pay_type IN ('monthly','hourly')),
    base_salary            numeric(12,2) CHECK (base_salary >= 0),   -- per month
    hourly_rate            numeric(10,2) CHECK (hourly_rate >= 0),
    tax_id                 text,                                 -- PAN etc., for tax deducted at source
    bank_account_holder    text,
    bank_name              text,
    bank_account_number    text,                                 -- encrypt at application level
    bank_ifsc              text,
    notes                  text,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CHECK (termination_date IS NULL OR termination_date >= hire_date),
    CHECK ((pay_type = 'monthly' AND base_salary IS NOT NULL) OR (pay_type = 'hourly' AND hourly_rate IS NOT NULL))
);

CREATE TABLE shift_templates (                        -- reusable patterns: Morning, Evening, Closing
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    department text CHECK (department IN ('management','front_desk','shop','bar','kitchen','finance','admin')),
    start_time time NOT NULL,
    end_time   time NOT NULL,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE shifts (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(id),
    department  text NOT NULL CHECK (department IN ('management','front_desk','shop','bar','kitchen','finance','admin')),
    template_id bigint REFERENCES shift_templates(id),
    starts_at   timestamptz NOT NULL,
    ends_at     timestamptz NOT NULL,
    status      text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','completed','absent','cancelled')),
    notes       text,
    created_by  bigint REFERENCES users(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at),
    -- one person cannot be rostered on two overlapping shifts
    CONSTRAINT shifts_no_overlap EXCLUDE USING gist
        (employee_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status <> 'cancelled')
);

CREATE TABLE attendance_records (                     -- actual clock-in / clock-out (feeds payroll)
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(id),
    shift_id    bigint REFERENCES shifts(id),
    clock_in    timestamptz NOT NULL,
    clock_out   timestamptz,
    method      text NOT NULL DEFAULT 'manual' CHECK (method IN ('manual','qr','biometric','app')),
    notes       text,
    recorded_by bigint REFERENCES users(id),
    CHECK (clock_out IS NULL OR clock_out > clock_in)
);

CREATE TABLE leave_types (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name              text NOT NULL UNIQUE,
    is_paid           boolean NOT NULL DEFAULT true,
    annual_quota_days numeric(4,1) CHECK (annual_quota_days >= 0),    -- NULL = not set / unlimited
    is_active         boolean NOT NULL DEFAULT true
);

CREATE TABLE leave_requests (
    id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id    bigint NOT NULL REFERENCES employees(id),
    leave_type_id  bigint NOT NULL REFERENCES leave_types(id),
    start_date     date NOT NULL,
    end_date       date NOT NULL,
    days_requested numeric(4,1) NOT NULL CHECK (days_requested > 0),
    reason         text,
    status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
    requested_at   timestamptz NOT NULL DEFAULT now(),
    decided_by     bigint REFERENCES users(id),           -- the manager (or owner for the manager's own leave)
    decided_at     timestamptz,
    decision_note  text,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date >= start_date),
    CHECK (status = 'pending' OR status = 'cancelled' OR decided_by IS NOT NULL)
);

CREATE TABLE payroll_runs (                           -- one run per month
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    period_month date NOT NULL UNIQUE CHECK (extract(day FROM period_month) = 1),   -- first day of month
    status       text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','paid')),
    created_by   bigint REFERENCES users(id),
    approved_by  bigint REFERENCES users(id),
    approved_at  timestamptz,
    paid_at      timestamptz,
    notes        text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payroll_items (                          -- one payslip per employee per run
    id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payroll_run_id        bigint NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
    employee_id           bigint NOT NULL REFERENCES employees(id),
    days_worked           numeric(5,1) NOT NULL DEFAULT 0,
    hours_worked          numeric(7,2),
    unpaid_leave_days     numeric(4,1) NOT NULL DEFAULT 0,
    base_pay              numeric(12,2) NOT NULL DEFAULT 0 CHECK (base_pay >= 0),
    overtime_pay          numeric(12,2) NOT NULL DEFAULT 0 CHECK (overtime_pay >= 0),
    allowances            numeric(12,2) NOT NULL DEFAULT 0 CHECK (allowances >= 0),
    gross_pay             numeric(12,2) GENERATED ALWAYS AS (base_pay + overtime_pay + allowances) STORED,
    unpaid_leave_deduction numeric(12,2) NOT NULL DEFAULT 0 CHECK (unpaid_leave_deduction >= 0),
    tax_deducted          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_deducted >= 0),
    other_deductions      numeric(12,2) NOT NULL DEFAULT 0 CHECK (other_deductions >= 0),
    net_pay               numeric(12,2) GENERATED ALWAYS AS
                              (base_pay + overtime_pay + allowances
                               - unpaid_leave_deduction - tax_deducted - other_deductions) STORED,
    payment_status        text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','paid')),
    paid_at               timestamptz,
    payment_method        text CHECK (payment_method IN ('cash','card','upi','online','bank_transfer','cheque')),
    payment_reference     text,
    UNIQUE (payroll_run_id, employee_id)
);


-- =====================================================================================
-- 4. MEMBERS & CUSTOMERS
-- =====================================================================================

CREATE TABLE guardians (                              -- parent / guardian of a Junior member
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name    text NOT NULL,
    phone        text NOT NULL,
    email        text,
    relationship text,                                 -- mother, father, guardian...
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- The three tiers: Gold (premium, full access), Silver (standard), Junior (under 18, discounted).
CREATE TABLE membership_plans (
    id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code                  text NOT NULL UNIQUE,         -- 'gold', 'silver', 'junior'
    name                  text NOT NULL,
    description           text,
    fee                   numeric(10,2) NOT NULL CHECK (fee >= 0),
    duration_months       smallint NOT NULL CHECK (duration_months > 0),
    joining_fee           numeric(10,2) NOT NULL DEFAULT 0 CHECK (joining_fee >= 0),
    min_age               smallint CHECK (min_age >= 0),
    max_age               smallint,                     -- Junior: 17
    shop_discount_pct     numeric(5,2) NOT NULL DEFAULT 0 CHECK (shop_discount_pct BETWEEN 0 AND 100),
    bar_discount_pct      numeric(5,2) NOT NULL DEFAULT 0 CHECK (bar_discount_pct  BETWEEN 0 AND 100),
    can_join_social_play  boolean NOT NULL DEFAULT true,
    is_active             boolean NOT NULL DEFAULT true,
    sort_order            smallint NOT NULL DEFAULT 0,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CHECK (min_age IS NULL OR max_age IS NULL OR max_age >= min_age)
);
-- Court prices per plan (free / discounted / walk-in) live in court_rates (section 5).

CREATE TABLE plan_benefits (                          -- bullet points for the website / plan comparison
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    plan_id     bigint NOT NULL REFERENCES membership_plans(id) ON DELETE CASCADE,
    description text NOT NULL,
    sort_order  smallint NOT NULL DEFAULT 0
);

CREATE TABLE members (
    id                      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_code             text NOT NULL UNIQUE,        -- number on the card; what staff type at the desk
    qr_token                text NOT NULL UNIQUE DEFAULT replace(gen_random_uuid()::text, '-', ''),
    user_id                 bigint UNIQUE REFERENCES users(id),   -- online login (NULL = desk-only member)
    full_name               text NOT NULL,
    date_of_birth           date NOT NULL CHECK (date_of_birth <= current_date),
    phone                   text NOT NULL,
    email                   text,
    address_line1           text,
    address_line2           text,
    city                    text,
    postal_code             text,
    photo_url               text,                        -- so staff can recognise them quickly
    emergency_contact_name  text,
    emergency_contact_phone text,
    guardian_id             bigint REFERENCES guardians(id),
    status                  text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','left')),
    joined_on               date NOT NULL DEFAULT current_date,
    registered_by           bigint REFERENCES users(id), -- front-desk user who signed them up
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    -- ASSUMPTION A1: anyone under 18 must have a guardian on file
    CONSTRAINT members_minor_needs_guardian
        CHECK (guardian_id IS NOT NULL OR date_of_birth <= current_date - interval '18 years')
);

-- A member's plan over time. Renewal, upgrade, downgrade = a NEW row linked to the previous one.
CREATE TABLE memberships (
    id                     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id              bigint NOT NULL REFERENCES members(id),
    plan_id                bigint NOT NULL REFERENCES membership_plans(id),
    start_date             date NOT NULL,
    end_date               date NOT NULL,               -- expiry; reminders are driven by this
    status                 text NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending','active','expired','cancelled','changed')),
                           -- 'changed' = replaced by a different plan before its end date
    started_as             text NOT NULL DEFAULT 'new' CHECK (started_as IN ('new','renewal','upgrade','downgrade')),
    previous_membership_id bigint REFERENCES memberships(id),
    auto_renew             boolean NOT NULL DEFAULT false,
    fee_charged            numeric(10,2) NOT NULL CHECK (fee_charged >= 0),        -- snapshot of plan fee
    joining_fee_charged    numeric(10,2) NOT NULL DEFAULT 0 CHECK (joining_fee_charged >= 0),
    cancelled_at           timestamptz,
    cancelled_by           bigint REFERENCES users(id),
    cancellation_reason    text,
    created_by             bigint REFERENCES users(id),
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date >= start_date),
    CONSTRAINT memberships_no_overlap EXCLUDE USING gist
        (member_id WITH =, daterange(start_date, end_date, '[]') WITH &&)
        WHERE (status IN ('pending','active'))
);

CREATE TABLE guests (                                 -- walk-ins / non-members who pay the walk-in rate
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name           text NOT NULL,
    phone               text,
    email               text,
    source              text NOT NULL DEFAULT 'walk_in' CHECK (source IN ('walk_in','phone','website','bar')),
    converted_member_id bigint REFERENCES members(id),   -- set when a guest later joins
    notes               text,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE business_clients (                       -- companies the club invoices
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    company_name        text NOT NULL,
    contact_person      text,
    email               text,
    phone               text,
    billing_address1    text,
    billing_address2    text,
    city                text,
    state               text,
    postal_code         text,
    tax_id              text,                          -- client GSTIN
    payment_terms_days  smallint NOT NULL DEFAULT 15 CHECK (payment_terms_days >= 0),
    status              text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
    notes               text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE member_notes (                           -- staff notes shown on the member's profile
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id  bigint NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    note       text NOT NULL,
    is_pinned  boolean NOT NULL DEFAULT false,
    created_by bigint NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);


-- =====================================================================================
-- 5. COURTS & BOOKINGS
-- =====================================================================================

CREATE TABLE sports (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name      text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE courts (
    id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name                  text NOT NULL UNIQUE,         -- 'Court 1', 'Padel A'
    sport_id              bigint NOT NULL REFERENCES sports(id),
    surface               text,                         -- clay, hard, synthetic, turf...
    is_indoor             boolean NOT NULL DEFAULT false,
    social_play_capacity  smallint CHECK (social_play_capacity > 0),   -- default people per court in social play
    status                text NOT NULL DEFAULT 'active' CHECK (status IN ('active','maintenance','closed')),
    notes                 text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE court_operating_hours (                  -- when each court can be booked
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    court_id    bigint NOT NULL REFERENCES courts(id) ON DELETE CASCADE,
    day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    open_time   time NOT NULL,
    close_time  time NOT NULL,
    UNIQUE (court_id, day_of_week),
    CHECK (close_time > open_time)
);

-- Price list. plan_id NULL = walk-in / non-member rate. price 0 = free (e.g. Gold).
CREATE TABLE court_rates (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sport_id     bigint NOT NULL REFERENCES sports(id),
    plan_id      bigint REFERENCES membership_plans(id),
    applies_to   text NOT NULL DEFAULT 'exclusive_booking'
                    CHECK (applies_to IN ('exclusive_booking','social_play_per_person')),
    days_of_week smallint[] CHECK (days_of_week IS NULL OR days_of_week <@ ARRAY[0,1,2,3,4,5,6]::smallint[]),
    start_time   time,                                  -- optional peak / off-peak band
    end_time     time,
    price        numeric(10,2) NOT NULL CHECK (price >= 0),   -- per session (or per person for social play)
    valid_from   date NOT NULL DEFAULT current_date,
    valid_to     date,
    is_active    boolean NOT NULL DEFAULT true,
    CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CHECK ((start_time IS NULL) = (end_time IS NULL))
);

-- The physical occupancy of a court. THIS is what must never overlap.
--   exclusive : one booking owns the court for the session
--   social    : many people share the court (Friday-night social play)
--   blocked   : maintenance, tournament, private hire
CREATE TABLE court_reservations (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    court_id         bigint NOT NULL REFERENCES courts(id),
    starts_at        timestamptz NOT NULL,
    ends_at          timestamptz NOT NULL,
    reservation_type text NOT NULL CHECK (reservation_type IN ('exclusive','social','blocked')),
    status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active','cancelled')),
    social_title     text,                              -- 'Friday Night Social'
    social_capacity  smallint CHECK (social_capacity > 0),
    block_reason     text,
    created_by       bigint REFERENCES users(id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at),
    CHECK ((reservation_type = 'social') = (social_capacity IS NOT NULL)),
    UNIQUE (id, reservation_type),
    CONSTRAINT court_no_double_booking EXCLUDE USING gist
        (court_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status = 'active')
    -- session length (60 min) and slot start (:00 / :30) come from club_settings and are
    -- validated by the application, so the club can change them without a schema change.
);

-- A person's booking on a reservation. Exclusive reservation = one booking; social = many.
CREATE TABLE bookings (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_ref       text NOT NULL UNIQUE,
    reservation_id    bigint NOT NULL,
    reservation_type  text NOT NULL CHECK (reservation_type IN ('exclusive','social')),
    member_id         bigint REFERENCES members(id),
    guest_id          bigint REFERENCES guests(id),
    membership_id     bigint REFERENCES memberships(id),   -- the plan in force when booked
    booked_via        text NOT NULL CHECK (booked_via IN ('member_app','website','front_desk','phone','walk_in')),
    booked_by         bigint REFERENCES users(id),         -- who made it (member, receptionist; NULL for public visitor)
    is_trial          boolean NOT NULL DEFAULT false,      -- trial session booked from the website
    rate_id           bigint REFERENCES court_rates(id),
    price_basis       text NOT NULL DEFAULT 'walk_in_rate'
                         CHECK (price_basis IN ('member_rate','walk_in_rate','plan_included','trial','complimentary')),
    amount_charged    numeric(10,2) NOT NULL DEFAULT 0 CHECK (amount_charged >= 0),   -- 0 = free for this plan
    status            text NOT NULL DEFAULT 'confirmed'
                         CHECK (status IN ('confirmed','checked_in','completed','cancelled','no_show')),
    checked_in_at     timestamptz,
    cancelled_at      timestamptz,
    cancelled_by      bigint REFERENCES users(id),
    cancellation_reason text,
    notes             text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(member_id, guest_id) = 1),
    FOREIGN KEY (reservation_id, reservation_type) REFERENCES court_reservations (id, reservation_type)
);
-- an exclusive reservation can have only one live booking
CREATE UNIQUE INDEX uq_one_live_exclusive_booking
    ON bookings (reservation_id) WHERE reservation_type = 'exclusive' AND status <> 'cancelled';
-- a person cannot join the same social session twice
CREATE UNIQUE INDEX uq_social_member_once
    ON bookings (reservation_id, member_id) WHERE reservation_type = 'social' AND status <> 'cancelled' AND member_id IS NOT NULL;
CREATE UNIQUE INDEX uq_social_guest_once
    ON bookings (reservation_id, guest_id)  WHERE reservation_type = 'social' AND status <> 'cancelled' AND guest_id  IS NOT NULL;

CREATE TABLE check_ins (                              -- every time a member turns up
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id     bigint NOT NULL REFERENCES members(id),
    booking_id    bigint REFERENCES bookings(id),
    checked_in_at timestamptz NOT NULL DEFAULT now(),
    method        text NOT NULL DEFAULT 'member_code' CHECK (method IN ('qr','member_code','name_search','phone')),
    recorded_by   bigint REFERENCES users(id),
    notes         text
);

-- Booking rules enforced in the database -------------------------------------------------
CREATE OR REPLACE FUNCTION fn_bookings_before_insert() RETURNS trigger AS $$
DECLARE
    v_capacity smallint;
    v_day      date;
    v_tz       text;
    v_limit    int;
    v_count    int;
BEGIN
    IF NEW.status = 'cancelled' THEN
        RETURN NEW;
    END IF;

    SELECT COALESCE((SELECT timezone FROM club_profile LIMIT 1), 'UTC') INTO v_tz;

    -- lock the reservation row so two simultaneous bookings are processed one after the other
    SELECT r.social_capacity, (r.starts_at AT TIME ZONE v_tz)::date
      INTO v_capacity, v_day
      FROM court_reservations r
     WHERE r.id = NEW.reservation_id
       FOR UPDATE;

    -- (a) social play: never more people than the session capacity
    IF NEW.reservation_type = 'social' THEN
        SELECT count(*) INTO v_count
          FROM bookings b
         WHERE b.reservation_id = NEW.reservation_id AND b.status <> 'cancelled';
        IF v_count >= v_capacity THEN
            RAISE EXCEPTION 'Social session is full (capacity %)', v_capacity USING ERRCODE = '23514';
        END IF;
    END IF;

    -- (b) a member can play at most N times a day (ASSUMPTION A2: social play counts too)
    IF NEW.member_id IS NOT NULL THEN
        SELECT NULLIF(value, '')::int INTO v_limit
          FROM club_settings WHERE key = 'max_bookings_per_member_per_day';
        IF v_limit IS NOT NULL THEN
            PERFORM pg_advisory_xact_lock(hashtextextended('booking_limit:' || NEW.member_id, 0));
            SELECT count(*) INTO v_count
              FROM bookings b
              JOIN court_reservations r ON r.id = b.reservation_id
             WHERE b.member_id = NEW.member_id
               AND b.status <> 'cancelled'
               AND (r.starts_at AT TIME ZONE v_tz)::date = v_day;
            IF v_count >= v_limit THEN
                RAISE EXCEPTION 'Member % already has % booking(s) on % (daily limit %)',
                    NEW.member_id, v_count, v_day, v_limit USING ERRCODE = '23514';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bookings_before_insert
    BEFORE INSERT ON bookings FOR EACH ROW EXECUTE FUNCTION fn_bookings_before_insert();

-- When an exclusive booking is cancelled, free the court straight away.
CREATE OR REPLACE FUNCTION fn_release_court_on_cancel() RETURNS trigger AS $$
BEGIN
    IF NEW.reservation_type = 'exclusive' AND NEW.status = 'cancelled' AND OLD.status <> 'cancelled' THEN
        UPDATE court_reservations SET status = 'cancelled' WHERE id = NEW.reservation_id;
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bookings_release_court
    AFTER UPDATE OF status ON bookings FOR EACH ROW EXECUTE FUNCTION fn_release_court_on_cancel();


-- =====================================================================================
-- 6. TAX
-- =====================================================================================

CREATE TABLE tax_rates (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name      text NOT NULL UNIQUE,                     -- 'GST 18%'
    rate_pct  numeric(5,2) NOT NULL CHECK (rate_pct BETWEEN 0 AND 100),
    is_active boolean NOT NULL DEFAULT true
);


-- =====================================================================================
-- 7. GEAR SHOP & STOCK   (counter sales and online orders share the same stock)
-- =====================================================================================

CREATE TABLE product_categories (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,                    -- rackets, balls, shoes, accessories, apparel
    parent_id  bigint REFERENCES product_categories(id),
    sort_order smallint NOT NULL DEFAULT 0,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE products (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id      bigint NOT NULL REFERENCES product_categories(id),
    name             text NOT NULL,
    brand            text,
    description      text,
    base_price       numeric(12,2) NOT NULL CHECK (base_price >= 0),     -- selling price, before tax
    cost_price       numeric(12,2) CHECK (cost_price >= 0),
    tax_rate_id      bigint NOT NULL REFERENCES tax_rates(id),
    image_url        text,
    is_listed_online boolean NOT NULL DEFAULT true,      -- visible on the website / member app
    is_active        boolean NOT NULL DEFAULT true,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Stock is held per variant (shoe size, colour...). A product with no options still has one variant.
CREATE TABLE product_variants (
    id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id     bigint NOT NULL REFERENCES products(id),
    sku            text NOT NULL UNIQUE,
    barcode        text UNIQUE,
    size           text,
    color          text,
    price_override numeric(12,2) CHECK (price_override >= 0),            -- NULL = use products.base_price
    stock_on_hand  integer NOT NULL DEFAULT 0 CHECK (stock_on_hand >= 0),  -- physically on the shelf
    stock_reserved integer NOT NULL DEFAULT 0 CHECK (stock_reserved >= 0), -- held for online orders awaiting pickup
    reorder_level  integer NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),  -- low-stock alert threshold
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
-- available to sell = stock_on_hand - stock_reserved   (see view v_low_stock)

CREATE TABLE suppliers (
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name               text NOT NULL,
    contact_person     text,
    phone              text,
    email              text,
    address            text,
    tax_id             text,
    payment_terms_days smallint NOT NULL DEFAULT 30 CHECK (payment_terms_days >= 0),
    is_active          boolean NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE purchase_orders (                        -- restocking from a supplier
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    po_number   text NOT NULL UNIQUE,
    supplier_id bigint NOT NULL REFERENCES suppliers(id),
    status      text NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft','ordered','partially_received','received','cancelled')),
    ordered_at  timestamptz,
    expected_on date,
    received_at timestamptz,
    notes       text,
    created_by  bigint REFERENCES users(id),
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE purchase_order_items (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    variant_id        bigint NOT NULL REFERENCES product_variants(id),
    quantity_ordered  integer NOT NULL CHECK (quantity_ordered > 0),
    quantity_received integer NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    unit_cost         numeric(12,2) NOT NULL CHECK (unit_cost >= 0),
    line_total        numeric(12,2) GENERATED ALWAYS AS (quantity_ordered * unit_cost) STORED
);

-- Stock ledger: every change to stock_on_hand is a row here; the trigger below updates the variant.
CREATE TABLE stock_movements (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    variant_id      bigint NOT NULL REFERENCES product_variants(id),
    quantity_change integer NOT NULL CHECK (quantity_change <> 0),      -- + in, - out
    reason          text NOT NULL CHECK (reason IN
                       ('opening_stock','purchase_received','sale','return','adjustment','damaged','lost')),
    reference_type  text CHECK (reference_type IN ('shop_order','purchase_order')),
    reference_id    bigint,
    balance_after   integer,                                            -- filled by the trigger
    notes           text,
    performed_by    bigint REFERENCES users(id),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION fn_apply_stock_movement() RETURNS trigger AS $$
BEGIN
    UPDATE product_variants
       SET stock_on_hand = stock_on_hand + NEW.quantity_change
     WHERE id = NEW.variant_id
    RETURNING stock_on_hand INTO NEW.balance_after;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unknown variant %', NEW.variant_id;
    END IF;
    RETURN NEW;      -- a movement that would push stock below 0 fails the CHECK on product_variants
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stock_movement
    BEFORE INSERT ON stock_movements FOR EACH ROW EXECUTE FUNCTION fn_apply_stock_movement();

-- Counter sale and online order are the SAME table, told apart by channel.
CREATE TABLE shop_orders (
    id                     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_no               text NOT NULL UNIQUE,
    member_id              bigint REFERENCES members(id),
    guest_id               bigint REFERENCES guests(id),               -- both NULL = anonymous counter sale
    channel                text NOT NULL CHECK (channel IN ('counter','online')),
    fulfillment_type       text NOT NULL CHECK (fulfillment_type IN ('in_store','pickup','delivery')),
    status                 text NOT NULL DEFAULT 'pending' CHECK (status IN
                              ('pending','confirmed','ready_for_pickup','out_for_delivery','completed','cancelled')),
    taken_by               bigint REFERENCES users(id),                -- staff who rang it up (counter)
    member_discount_pct    numeric(5,2) NOT NULL DEFAULT 0 CHECK (member_discount_pct BETWEEN 0 AND 100), -- snapshot of plan discount
    subtotal               numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total         numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total              numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    delivery_fee           numeric(10,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    total_amount           numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    delivery_address_line1 text,
    delivery_address_line2 text,
    delivery_city          text,
    delivery_postal_code   text,
    delivery_phone         text,
    delivery_notes         text,
    assigned_delivery_to   bigint REFERENCES employees(id),
    placed_at              timestamptz NOT NULL DEFAULT now(),
    ready_at               timestamptz,
    completed_at           timestamptz,
    cancelled_at           timestamptz,
    cancellation_reason    text,
    notes                  text,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(member_id, guest_id) <= 1),
    CHECK (channel = 'online' OR fulfillment_type = 'in_store'),
    CHECK (channel = 'counter' OR fulfillment_type <> 'in_store'),
    CHECK (fulfillment_type <> 'delivery' OR delivery_address_line1 IS NOT NULL),
    CHECK (channel = 'online' OR member_id IS NOT NULL OR guest_id IS NOT NULL OR taken_by IS NOT NULL)
);

CREATE TABLE shop_order_items (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    variant_id      bigint NOT NULL REFERENCES product_variants(id),
    product_name    text NOT NULL,                       -- snapshot (name + size/colour)
    quantity        integer NOT NULL CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0)
);


-- =====================================================================================
-- 8. BAR & CAFETERIA
-- =====================================================================================

CREATE TABLE bar_menu_categories (                    -- drinks, snacks, meals
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    sort_order smallint NOT NULL DEFAULT 0,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE bar_menu_items (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id  bigint NOT NULL REFERENCES bar_menu_categories(id),
    name         text NOT NULL,
    description  text,
    price        numeric(10,2) NOT NULL CHECK (price >= 0),          -- before tax
    tax_rate_id  bigint NOT NULL REFERENCES tax_rates(id),
    station      text NOT NULL DEFAULT 'bar' CHECK (station IN ('bar','kitchen')),   -- who prepares it
    is_available boolean NOT NULL DEFAULT true,           -- flip off when sold out
    is_active    boolean NOT NULL DEFAULT true,
    image_url    text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dining_tables (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_number text NOT NULL UNIQUE,
    seats        smallint NOT NULL CHECK (seats > 0),
    zone         text,                                   -- indoor, terrace, courtside
    status       text NOT NULL DEFAULT 'available' CHECK (status IN ('available','occupied','reserved','out_of_service'))
);

-- A tab = several orders settled together ("run a tab and pay before they leave").
CREATE TABLE bar_tabs (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tab_no     text NOT NULL UNIQUE,
    member_id  bigint REFERENCES members(id),
    guest_id   bigint REFERENCES guests(id),
    guest_name text,                                     -- quick label for an unregistered guest
    table_id   bigint REFERENCES dining_tables(id),
    status     text NOT NULL DEFAULT 'open' CHECK (status IN ('open','settled','void')),
    opened_by  bigint NOT NULL REFERENCES users(id),
    opened_at  timestamptz NOT NULL DEFAULT now(),
    settled_at timestamptz,
    closed_by  bigint REFERENCES users(id),
    CHECK (num_nonnulls(member_id, guest_id) <= 1)
);

CREATE TABLE bar_orders (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_no            text NOT NULL UNIQUE,
    tab_id              bigint REFERENCES bar_tabs(id),
    table_id            bigint REFERENCES dining_tables(id),
    member_id           bigint REFERENCES members(id),
    guest_id            bigint REFERENCES guests(id),
    taken_by            bigint NOT NULL REFERENCES users(id),        -- the staff member on shift
    status              text NOT NULL DEFAULT 'placed'
                           CHECK (status IN ('placed','preparing','ready','served','cancelled')),
    member_discount_pct numeric(5,2) NOT NULL DEFAULT 0 CHECK (member_discount_pct BETWEEN 0 AND 100),  -- applied automatically
    subtotal            numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total      numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total           numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount        numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes               text,
    placed_at           timestamptz NOT NULL DEFAULT now(),
    served_at           timestamptz,
    cancelled_at        timestamptz,
    cancellation_reason text,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(member_id, guest_id) <= 1)
);

CREATE TABLE bar_order_items (
    id                   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id             bigint NOT NULL REFERENCES bar_orders(id) ON DELETE CASCADE,
    menu_item_id         bigint NOT NULL REFERENCES bar_menu_items(id),
    item_name            text NOT NULL,                  -- snapshot
    quantity             integer NOT NULL CHECK (quantity > 0),
    unit_price           numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount      numeric(10,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id          bigint REFERENCES tax_rates(id),
    tax_amount           numeric(10,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total           numeric(10,2) NOT NULL CHECK (line_total >= 0),
    station              text NOT NULL CHECK (station IN ('bar','kitchen')),
    kitchen_status       text NOT NULL DEFAULT 'pending'
                            CHECK (kitchen_status IN ('pending','preparing','ready','served','cancelled')),
    special_instructions text,
    ready_at             timestamptz
);


-- =====================================================================================
-- 9. ENQUIRIES (CRM)   handled by the receptionist
-- =====================================================================================

CREATE TABLE enquiries (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name           text NOT NULL,
    company_name        text,                              -- for corporate enquiries
    phone               text,
    email               text,
    source              text NOT NULL DEFAULT 'website_form'
                           CHECK (source IN ('website_form','trial_booking','phone','walk_in','email','referral','other')),
    enquiry_type        text NOT NULL DEFAULT 'membership'
                           CHECK (enquiry_type IN ('membership','trial_session','court_booking','shop','corporate','general')),
    interested_plan_id  bigint REFERENCES membership_plans(id),
    interested_sport_id bigint REFERENCES sports(id),
    message             text,
    status              text NOT NULL DEFAULT 'new'
                           CHECK (status IN ('new','contacted','quoted','trial_scheduled','won','lost')),
    assigned_to         bigint REFERENCES users(id),       -- the receptionist following it up
    next_follow_up_at   timestamptz,
    trial_booking_id    bigint REFERENCES bookings(id),
    converted_member_id bigint REFERENCES members(id),     -- set when they join
    business_client_id  bigint REFERENCES business_clients(id),
    lost_reason         text,
    closed_at           timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (phone IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE enquiry_activities (                      -- follow-up trail so nothing "vanishes"
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    enquiry_id    bigint NOT NULL REFERENCES enquiries(id) ON DELETE CASCADE,
    activity_type text NOT NULL CHECK (activity_type IN
                     ('note','call','email','sms','whatsapp','visit','status_change','quote_sent')),
    summary       text NOT NULL,
    performed_by  bigint REFERENCES users(id),
    occurred_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE quotes (
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    quote_no           text NOT NULL UNIQUE,
    enquiry_id         bigint NOT NULL REFERENCES enquiries(id),
    plan_id            bigint REFERENCES membership_plans(id),
    business_client_id bigint REFERENCES business_clients(id),
    status             text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','accepted','rejected','expired')),
    valid_until        date,
    subtotal           numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total     numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount       numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    sent_at            timestamptz,
    sent_via           text CHECK (sent_via IN ('email','whatsapp','sms','print')),
    accepted_at        timestamptz,
    notes              text,
    created_by         bigint REFERENCES users(id),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE quote_items (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    quote_id        bigint NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
    description     text NOT NULL,
    quantity        numeric(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0)
);


-- =====================================================================================
-- 10. FINANCE
-- =====================================================================================

-- One invoice table for everything: counter receipts, bar bills, court fees, memberships,
-- and invoices to business clients. Each LINE says which part of the club earned it.
CREATE TABLE invoices (
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    invoice_no         text NOT NULL UNIQUE,
    member_id          bigint REFERENCES members(id),
    guest_id           bigint REFERENCES guests(id),
    business_client_id bigint REFERENCES business_clients(id),
    bill_to_name       text,                              -- snapshot name printed on the invoice
    quote_id           bigint REFERENCES quotes(id),
    status             text NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft','issued','partially_paid','paid','void')),
    issue_date         date NOT NULL DEFAULT current_date,
    due_date           date,                              -- overdue = issued/partially_paid and due_date < today
    subtotal           numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total     numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount       numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    amount_paid        numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),   -- kept in sync by trigger
    balance_due        numeric(12,2) GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
    notes              text,
    issued_by          bigint REFERENCES users(id),
    voided_at          timestamptz,
    voided_by          bigint REFERENCES users(id),
    void_reason        text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(member_id, guest_id, business_client_id) <= 1)
);

CREATE TABLE invoice_items (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    invoice_id      bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    source          text NOT NULL CHECK (source IN ('membership','court_booking','shop','bar','other')),  -- "from where"
    description     text NOT NULL,
    quantity        numeric(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0),       -- includes tax
    -- what this line bills (at most one):
    membership_id   bigint REFERENCES memberships(id),
    booking_id      bigint REFERENCES bookings(id),
    shop_order_id   bigint REFERENCES shop_orders(id),
    bar_order_id    bigint REFERENCES bar_orders(id),                     -- a tab settles as one line per order
    CHECK (num_nonnulls(membership_id, booking_id, shop_order_id, bar_order_id) <= 1),
    CHECK (membership_id IS NULL OR source = 'membership'),
    CHECK (booking_id    IS NULL OR source = 'court_booking'),
    CHECK (shop_order_id IS NULL OR source = 'shop'),
    CHECK (bar_order_id  IS NULL OR source = 'bar')
);

CREATE TABLE payments (
    id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receipt_no     text UNIQUE,
    invoice_id     bigint NOT NULL REFERENCES invoices(id),
    amount         numeric(12,2) NOT NULL CHECK (amount > 0),
    method         text NOT NULL CHECK (method IN ('cash','card','upi','online','bank_transfer','cheque')),
    status         text NOT NULL DEFAULT 'success' CHECK (status IN ('pending','success','failed')),
    gateway_name   text,                                  -- Razorpay, Stripe... for online payments
    transaction_ref text,                                 -- UPI ref / card auth / gateway txn id
    card_last4     char(4),
    received_by    bigint REFERENCES users(id),           -- NULL for online self-payments
    paid_at        timestamptz NOT NULL DEFAULT now(),
    notes          text,
    created_at     timestamptz NOT NULL DEFAULT now()
);
-- Payments are never deleted; corrections are made with refunds.

CREATE TABLE refunds (                                  -- e.g. cancelled booking, returned goods
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payment_id  bigint NOT NULL REFERENCES payments(id),
    amount      numeric(12,2) NOT NULL CHECK (amount > 0),
    method      text NOT NULL CHECK (method IN ('cash','card','upi','online','bank_transfer','cheque')),
    reason      text,
    refunded_by bigint NOT NULL REFERENCES users(id),
    refunded_at timestamptz NOT NULL DEFAULT now()
);

-- A payment can never be refunded for more than it was.
CREATE OR REPLACE FUNCTION fn_refunds_before_insert() RETURNS trigger AS $$
DECLARE
    v_paid     numeric(12,2);
    v_refunded numeric(12,2);
BEGIN
    SELECT amount INTO v_paid FROM payments WHERE id = NEW.payment_id FOR UPDATE;
    SELECT COALESCE(SUM(amount), 0) INTO v_refunded FROM refunds WHERE payment_id = NEW.payment_id;
    IF v_refunded + NEW.amount > v_paid THEN
        RAISE EXCEPTION 'Refund of % exceeds the refundable balance (%) of payment %',
            NEW.amount, v_paid - v_refunded, NEW.payment_id USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_refunds_before_insert BEFORE INSERT ON refunds
    FOR EACH ROW EXECUTE FUNCTION fn_refunds_before_insert();

-- Keep invoices.amount_paid and invoices.status in line with payments and refunds.
CREATE OR REPLACE FUNCTION fn_sync_invoice_payments(p_invoice_id bigint) RETURNS void AS $$
DECLARE
    v_paid numeric(12,2);
BEGIN
    SELECT COALESCE(SUM(p.amount) FILTER (WHERE p.status = 'success'), 0)
           - COALESCE((SELECT SUM(rf.amount) FROM refunds rf
                         JOIN payments p2 ON p2.id = rf.payment_id
                        WHERE p2.invoice_id = p_invoice_id), 0)
      INTO v_paid
      FROM payments p
     WHERE p.invoice_id = p_invoice_id;

    UPDATE invoices
       SET amount_paid = v_paid,
           status = CASE WHEN status IN ('draft','void') THEN status
                         WHEN v_paid >= total_amount      THEN 'paid'
                         WHEN v_paid > 0                  THEN 'partially_paid'
                         ELSE 'issued' END
     WHERE id = p_invoice_id;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_payments_sync() RETURNS trigger AS $$
BEGIN
    PERFORM fn_sync_invoice_payments(NEW.invoice_id);
    IF TG_OP = 'UPDATE' AND OLD.invoice_id <> NEW.invoice_id THEN
        PERFORM fn_sync_invoice_payments(OLD.invoice_id);
    END IF;
    RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_payments_sync AFTER INSERT OR UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION trg_payments_sync();

CREATE OR REPLACE FUNCTION trg_refunds_sync() RETURNS trigger AS $$
BEGIN
    PERFORM fn_sync_invoice_payments((SELECT invoice_id FROM payments WHERE id = NEW.payment_id));
    RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_refunds_sync AFTER INSERT ON refunds
    FOR EACH ROW EXECUTE FUNCTION trg_refunds_sync();

-- End-of-day cash-up per department ("what did the bar actually earn today?").
CREATE TABLE daily_closings (
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    business_date date NOT NULL,
    department    text NOT NULL CHECK (department IN ('courts','shop','bar','all')),
    total_sales   numeric(12,2) NOT NULL DEFAULT 0,
    cash_total    numeric(12,2) NOT NULL DEFAULT 0,
    card_total    numeric(12,2) NOT NULL DEFAULT 0,
    upi_total     numeric(12,2) NOT NULL DEFAULT 0,
    online_total  numeric(12,2) NOT NULL DEFAULT 0,
    other_total   numeric(12,2) NOT NULL DEFAULT 0,
    opening_cash  numeric(12,2) NOT NULL DEFAULT 0,
    expected_cash numeric(12,2) NOT NULL DEFAULT 0,       -- opening cash + cash sales - cash refunds
    counted_cash  numeric(12,2) NOT NULL DEFAULT 0,
    cash_variance numeric(12,2) GENERATED ALWAYS AS (counted_cash - expected_cash) STORED,
    closed_by     bigint NOT NULL REFERENCES users(id),
    closed_at     timestamptz NOT NULL DEFAULT now(),
    notes         text,
    UNIQUE (business_date, department)
);

CREATE TABLE expense_categories (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name      text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

-- Money going out (supplier bills, rent, utilities...). status 'unpaid' = something we owe.
CREATE TABLE expenses (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id       bigint NOT NULL REFERENCES expense_categories(id),
    supplier_id       bigint REFERENCES suppliers(id),
    purchase_order_id bigint REFERENCES purchase_orders(id),
    description       text NOT NULL,
    amount            numeric(12,2) NOT NULL CHECK (amount > 0),       -- total including tax
    tax_amount        numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),   -- input tax, for tax returns
    expense_date      date NOT NULL DEFAULT current_date,
    due_date          date,
    status            text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid','paid','void')),
    paid_at           timestamptz,
    payment_method    text CHECK (payment_method IN ('cash','card','upi','online','bank_transfer','cheque')),
    reference_no      text,
    receipt_url       text,
    recorded_by       bigint REFERENCES users(id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CHECK (status <> 'paid' OR paid_at IS NOT NULL)
);

CREATE TABLE tax_returns (                              -- "taxes to report"
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tax_type           text NOT NULL,                   -- 'GST', 'TDS', 'Income tax'...
    period_start       date NOT NULL,
    period_end         date NOT NULL,
    tax_collected      numeric(12,2) NOT NULL DEFAULT 0,   -- on sales
    tax_credit         numeric(12,2) NOT NULL DEFAULT 0,   -- on purchases / expenses
    net_payable        numeric(12,2) GENERATED ALWAYS AS (tax_collected - tax_credit) STORED,
    status             text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','filed','paid')),
    due_date           date,
    filed_at           timestamptz,
    filed_by           bigint REFERENCES users(id),
    paid_at            timestamptz,
    reference_no       text,
    notes              text,
    created_by         bigint REFERENCES users(id),
    created_at         timestamptz NOT NULL DEFAULT now(),
    CHECK (period_end >= period_start)
);

CREATE TABLE report_shares (                            -- owner shares "the numbers" with a partner, bank, accountant
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    report_type     text NOT NULL CHECK (report_type IN
                       ('daily_summary','weekly_summary','monthly_summary','revenue_by_source','payables','tax_summary','custom')),
    period_start    date NOT NULL,
    period_end      date NOT NULL,
    snapshot        jsonb NOT NULL,                      -- the figures frozen at the moment of sharing
    share_token     text NOT NULL UNIQUE DEFAULT replace(gen_random_uuid()::text, '-', ''),
    recipient_name  text,
    recipient_email text,
    expires_at      timestamptz,
    revoked_at      timestamptz,
    view_count      integer NOT NULL DEFAULT 0,
    created_by      bigint NOT NULL REFERENCES users(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    CHECK (period_end >= period_start)
);


-- =====================================================================================
-- 11. NOTIFICATIONS & AUDIT
-- =====================================================================================

CREATE TABLE notifications (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint REFERENCES users(id),
    recipient_contact text,                              -- email / phone for someone without a login
    type              text NOT NULL,                     -- enquiry_new, membership_expiring, low_stock,
                                                         -- leave_requested, leave_decided, order_ready, booking_confirmed...
    channel           text NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app','email','sms','whatsapp','push')),
    title             text NOT NULL,
    body              text,
    entity_type       text,                              -- what it is about, e.g. 'membership'
    entity_id         bigint,
    dedupe_key        text UNIQUE,                       -- e.g. 'membership_expiry:42:7d' so a reminder is sent once
    status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
    is_read           boolean NOT NULL DEFAULT false,
    read_at           timestamptz,
    scheduled_for     timestamptz NOT NULL DEFAULT now(),
    sent_at           timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CHECK (recipient_user_id IS NOT NULL OR recipient_contact IS NOT NULL)
);

CREATE TABLE audit_logs (                               -- who changed what (money, prices, roles, stock)
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     bigint REFERENCES users(id),
    action      text NOT NULL,                           -- 'create', 'update', 'delete', 'login', 'refund', 'void'...
    entity_type text NOT NULL,
    entity_id   bigint,
    old_values  jsonb,
    new_values  jsonb,
    ip_address  inet,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now()
);


-- =====================================================================================
-- 12. updated_at TRIGGERS  (every table that has an updated_at column)
-- =====================================================================================

DO $$
DECLARE t text;
BEGIN
    FOR t IN
        SELECT c.table_name FROM information_schema.columns c
          JOIN information_schema.tables tb ON tb.table_schema = c.table_schema AND tb.table_name = c.table_name
         WHERE c.table_schema = 'public' AND c.column_name = 'updated_at' AND tb.table_type = 'BASE TABLE'
    LOOP
        EXECUTE format('CREATE TRIGGER trg_%1$s_updated_at BEFORE UPDATE ON %1$I
                        FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t);
    END LOOP;
END $$;


-- =====================================================================================
-- 13. INDEXES  (exclusion constraints and UNIQUE columns already have their own)
-- =====================================================================================

CREATE INDEX idx_user_roles_role          ON user_roles (role_id);
CREATE INDEX idx_members_phone            ON members (phone);
CREATE INDEX idx_members_name             ON members (lower(full_name));
CREATE INDEX idx_memberships_member       ON memberships (member_id, status);
CREATE INDEX idx_memberships_expiry       ON memberships (end_date) WHERE status = 'active';
CREATE INDEX idx_guests_phone             ON guests (phone);
CREATE INDEX idx_member_notes_member      ON member_notes (member_id);
CREATE INDEX idx_court_res_start          ON court_reservations (starts_at);
CREATE INDEX idx_bookings_member          ON bookings (member_id, status);
CREATE INDEX idx_bookings_guest           ON bookings (guest_id);
CREATE INDEX idx_bookings_reservation     ON bookings (reservation_id);
CREATE INDEX idx_checkins_member          ON check_ins (member_id, checked_in_at DESC);
CREATE INDEX idx_court_rates_lookup       ON court_rates (sport_id, plan_id, applies_to) WHERE is_active;
CREATE INDEX idx_products_category        ON products (category_id);
CREATE INDEX idx_variants_product         ON product_variants (product_id);
CREATE INDEX idx_stock_mv_variant         ON stock_movements (variant_id, created_at DESC);
CREATE INDEX idx_shop_orders_member       ON shop_orders (member_id, placed_at DESC);
CREATE INDEX idx_shop_orders_status       ON shop_orders (status) WHERE status NOT IN ('completed','cancelled');
CREATE INDEX idx_shop_items_order         ON shop_order_items (order_id);
CREATE INDEX idx_bar_tabs_open            ON bar_tabs (status) WHERE status = 'open';
CREATE INDEX idx_bar_orders_tab           ON bar_orders (tab_id);
CREATE INDEX idx_bar_orders_member        ON bar_orders (member_id, placed_at DESC);
CREATE INDEX idx_bar_orders_placed        ON bar_orders (placed_at);
CREATE INDEX idx_bar_items_order          ON bar_order_items (order_id);
CREATE INDEX idx_bar_items_kitchen        ON bar_order_items (kitchen_status) WHERE station = 'kitchen' AND kitchen_status IN ('pending','preparing');
CREATE INDEX idx_enquiries_status         ON enquiries (status, assigned_to);
CREATE INDEX idx_enquiries_followup       ON enquiries (next_follow_up_at) WHERE status NOT IN ('won','lost');
CREATE INDEX idx_enq_activities_enquiry   ON enquiry_activities (enquiry_id, occurred_at);
CREATE INDEX idx_invoices_member          ON invoices (member_id);
CREATE INDEX idx_invoices_client          ON invoices (business_client_id);
CREATE INDEX idx_invoices_date            ON invoices (issue_date);
CREATE INDEX idx_invoices_open            ON invoices (due_date) WHERE status IN ('issued','partially_paid');
CREATE INDEX idx_invoice_items_invoice    ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_source     ON invoice_items (source);
CREATE INDEX idx_payments_invoice         ON payments (invoice_id);
CREATE INDEX idx_payments_paid_at         ON payments (paid_at);
CREATE INDEX idx_expenses_status          ON expenses (status, due_date);
CREATE INDEX idx_shifts_start             ON shifts (starts_at);
CREATE INDEX idx_attendance_employee      ON attendance_records (employee_id, clock_in);
CREATE INDEX idx_leave_employee           ON leave_requests (employee_id, status);
CREATE INDEX idx_payroll_items_employee   ON payroll_items (employee_id);
CREATE INDEX idx_notifications_user       ON notifications (recipient_user_id, is_read);
CREATE INDEX idx_notifications_pending    ON notifications (scheduled_for) WHERE status = 'pending';
CREATE INDEX idx_audit_entity             ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_user               ON audit_logs (user_id, created_at DESC);


-- =====================================================================================
-- 14. SEED DATA  (reference data only - plans, prices and people are entered in the app)
-- =====================================================================================

INSERT INTO roles (id, code, name, description) VALUES
 (1, 'owner',        'Owner',                    'Sees revenue, payables and performance; can share reports'),
 (2, 'manager',      'Manager',                  'Runs day-to-day operations, shifts, leave, pricing and stock (one person)'),
 (3, 'front_desk',   'Front desk / Receptionist','Sign-ups, bookings, walk-ins, phone queries, enquiries and follow-up'),
 (4, 'shop_staff',   'Shop staff',               'Counter sales, stock, online order fulfilment'),
 (5, 'bar_staff',    'Bar / cafe staff',         'Orders, tables, tabs, kitchen, bar payments'),
 (6, 'accountant',   'Accountant / Finance',     'Invoicing, payroll, expenses, tax reporting'),
 (7, 'member',       'Member',                   'Self-service: bookings, shop orders, membership, tab'),
 (8, 'system_admin', 'System admin',             'Users, permissions and system settings');

INSERT INTO permissions (code, module, description) VALUES
 ('member.view',       'members',    'View member profiles and history'),
 ('member.manage',     'members',    'Register and edit members, add notes'),
 ('membership.manage', 'members',    'Sell, renew, change and cancel memberships'),
 ('plan.manage',       'members',    'Edit plans, benefits and fees'),
 ('booking.view',      'courts',     'See the court schedule and bookings'),
 ('booking.manage',    'courts',     'Create, move and cancel bookings; check members in'),
 ('court.manage',      'courts',     'Courts, hours, rates, social sessions, maintenance blocks'),
 ('shop.sell',         'shop',       'Ring up counter sales'),
 ('shop.fulfil',       'shop',       'Process online orders (pickup / delivery)'),
 ('product.manage',    'shop',       'Edit the product catalogue and prices'),
 ('inventory.view',    'shop',       'See stock levels and low-stock alerts'),
 ('inventory.manage',  'shop',       'Stock adjustments, suppliers, purchase orders'),
 ('bar.order',         'bar',        'Take orders, manage tables and tabs'),
 ('bar.kitchen',       'bar',        'See and update the kitchen queue'),
 ('bar.menu.manage',   'bar',        'Edit the bar / cafe menu and prices'),
 ('payment.take',      'finance',    'Record payments'),
 ('payment.refund',    'finance',    'Issue refunds'),
 ('invoice.view',      'finance',    'View invoices and receipts'),
 ('invoice.manage',    'finance',    'Create, issue and void invoices'),
 ('finance.view',      'finance',    'Revenue, payables and financial dashboards'),
 ('expense.manage',    'finance',    'Record and pay expenses'),
 ('tax.manage',        'finance',    'Prepare and file tax returns'),
 ('closing.manage',    'finance',    'Daily cash-up / closing'),
 ('report.view',       'reports',    'Operational reports'),
 ('report.share',      'reports',    'Share reports outside the club'),
 ('employee.view',     'hr',         'View staff records (no pay details)'),
 ('employee.manage',   'hr',         'Create and edit staff, including pay details'),
 ('shift.manage',      'hr',         'Create and edit staff shifts'),
 ('leave.request',     'hr',         'Request own leave'),
 ('leave.approve',     'hr',         'Approve or reject leave'),
 ('payroll.manage',    'hr',         'Run and approve payroll'),
 ('enquiry.manage',    'crm',        'Handle enquiries, follow-ups and quotes'),
 ('user.manage',       'admin',      'Create users and assign roles'),
 ('role.manage',       'admin',      'Edit what each role can do'),
 ('settings.manage',   'admin',      'Change club profile and booking rules'),
 ('audit.view',        'admin',      'View the audit log'),
 ('portal.use',        'portal',     'Member self-service (book, order, view own data)');

-- Owner: everything
INSERT INTO role_permissions (role_id, permission_id) SELECT 1, id FROM permissions;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM (VALUES
    -- manager
    ('manager','member.view'),('manager','member.manage'),('manager','membership.manage'),('manager','plan.manage'),
    ('manager','booking.view'),('manager','booking.manage'),('manager','court.manage'),
    ('manager','shop.sell'),('manager','shop.fulfil'),('manager','product.manage'),
    ('manager','inventory.view'),('manager','inventory.manage'),
    ('manager','bar.order'),('manager','bar.kitchen'),('manager','bar.menu.manage'),
    ('manager','payment.take'),('manager','payment.refund'),('manager','invoice.view'),
    ('manager','report.view'),('manager','closing.manage'),
    ('manager','employee.view'),('manager','shift.manage'),('manager','leave.request'),('manager','leave.approve'),
    ('manager','enquiry.manage'),
    -- front desk
    ('front_desk','member.view'),('front_desk','member.manage'),('front_desk','membership.manage'),
    ('front_desk','booking.view'),('front_desk','booking.manage'),
    ('front_desk','payment.take'),('front_desk','invoice.view'),
    ('front_desk','enquiry.manage'),('front_desk','shift.manage'),('front_desk','leave.request'),
    -- shop staff
    ('shop_staff','member.view'),('shop_staff','shop.sell'),('shop_staff','shop.fulfil'),
    ('shop_staff','inventory.view'),('shop_staff','inventory.manage'),
    ('shop_staff','payment.take'),('shop_staff','leave.request'),
    -- bar / cafe staff
    ('bar_staff','member.view'),('bar_staff','bar.order'),('bar_staff','bar.kitchen'),
    ('bar_staff','payment.take'),('bar_staff','leave.request'),
    -- accountant
    ('accountant','invoice.view'),('accountant','invoice.manage'),('accountant','payment.take'),
    ('accountant','finance.view'),('accountant','expense.manage'),('accountant','tax.manage'),
    ('accountant','closing.manage'),('accountant','report.view'),('accountant','report.share'),
    ('accountant','employee.view'),('accountant','employee.manage'),('accountant','payroll.manage'),
    ('accountant','leave.request'),
    -- member
    ('member','portal.use'),
    -- system admin
    ('system_admin','user.manage'),('system_admin','role.manage'),
    ('system_admin','settings.manage'),('system_admin','audit.view')
  ) AS v(role_code, perm_code)
  JOIN roles r       ON r.code = v.role_code
  JOIN permissions p ON p.code = v.perm_code;

INSERT INTO club_profile (name) VALUES ('The Champions Club');

INSERT INTO club_settings (key, value, description) VALUES
 ('session_duration_minutes',        '60',    'A court session lasts one hour (problem statement)'),
 ('slot_interval_minutes',           '30',    'A new slot opens every half hour (problem statement)'),
 ('max_bookings_per_member_per_day', '2',     'Each member can play at most twice a day (problem statement)'),
 ('advance_booking_days',            '14',    'ASSUMPTION: how far ahead courts can be booked'),
 ('cancellation_cutoff_hours',       '4',     'ASSUMPTION: free cancellation until this many hours before start'),
 ('membership_expiry_reminder_days', '30,7,1','ASSUMPTION: days before expiry when reminders go out');

INSERT INTO sports (name) VALUES ('Tennis'), ('Padel'), ('Badminton'), ('Cricket');       -- ASSUMPTION A5

INSERT INTO tax_rates (name, rate_pct) VALUES                                               -- ASSUMPTION A3 (placeholders)
 ('Exempt 0%', 0), ('GST 5%', 5), ('GST 12%', 12), ('GST 18%', 18);

INSERT INTO product_categories (name, sort_order) VALUES
 ('Rackets', 1), ('Balls', 2), ('Shoes', 3), ('Accessories', 4), ('Apparel', 5);

INSERT INTO bar_menu_categories (name, sort_order) VALUES ('Drinks', 1), ('Snacks', 2), ('Meals', 3);

INSERT INTO leave_types (name, is_paid) VALUES
 ('Casual leave', true), ('Sick leave', true), ('Earned leave', true), ('Unpaid leave', false);

INSERT INTO expense_categories (name) VALUES
 ('Inventory purchases'), ('Rent'), ('Utilities'), ('Maintenance & repairs'),
 ('Salaries'), ('Taxes'), ('Marketing'), ('Other');


-- =====================================================================================
-- 15. REPORTING VIEWS & AVAILABILITY FUNCTION
-- =====================================================================================

-- Free slots for the website, the phone, and the 6 pm rush:  SELECT * FROM fn_free_slots(current_date, current_date + 6);
CREATE OR REPLACE FUNCTION fn_free_slots(p_from date, p_to date, p_sport_id bigint DEFAULT NULL)
RETURNS TABLE (court_id bigint, court_name text, sport_id bigint, slot_start timestamptz, slot_end timestamptz)
LANGUAGE sql STABLE AS $$
    WITH cfg AS (
        SELECT COALESCE((SELECT value::int FROM club_settings WHERE key = 'session_duration_minutes'), 60) AS dur,
               COALESCE((SELECT value::int FROM club_settings WHERE key = 'slot_interval_minutes'), 30)    AS step,
               COALESCE((SELECT timezone FROM club_profile LIMIT 1), 'UTC')                                AS tz
    ),
    cand AS (
        SELECT c.id AS cid, c.name AS cname, c.sport_id AS sid,
               ((d.dt + h.open_time) AT TIME ZONE cfg.tz) + make_interval(mins => n * cfg.step) AS s,
               ((d.dt + h.open_time) AT TIME ZONE cfg.tz) + make_interval(mins => n * cfg.step + cfg.dur) AS e
          FROM cfg
         CROSS JOIN generate_series(p_from::timestamp, p_to::timestamp, interval '1 day') AS d(dt)
          JOIN court_operating_hours h ON h.day_of_week = EXTRACT(DOW FROM d.dt)::int
          JOIN courts c ON c.id = h.court_id AND c.status = 'active'
         CROSS JOIN LATERAL generate_series(
                0, ((EXTRACT(EPOCH FROM (h.close_time - h.open_time)) / 60)::int - cfg.dur) / cfg.step
              ) AS n
         WHERE p_sport_id IS NULL OR c.sport_id = p_sport_id
    )
    SELECT cid, cname, sid, s, e
      FROM cand
     WHERE s > now()
       AND NOT EXISTS (SELECT 1 FROM court_reservations r
                        WHERE r.court_id = cand.cid AND r.status = 'active'
                          AND tstzrange(r.starts_at, r.ends_at) && tstzrange(cand.s, cand.e))
     ORDER BY s, cname;
$$;

-- Everything a member has done at the club (for the front desk "see their history").
CREATE VIEW v_member_history AS
SELECT b.member_id, r.starts_at AS event_at, 'court_booking'::text AS event_type, b.id AS ref_id,
       c.name || ' (' || b.status || ')' AS summary, b.amount_charged AS amount
  FROM bookings b JOIN court_reservations r ON r.id = b.reservation_id JOIN courts c ON c.id = r.court_id
 WHERE b.member_id IS NOT NULL
UNION ALL
SELECT ci.member_id, ci.checked_in_at, 'check_in', ci.id, 'Checked in (' || ci.method || ')', NULL
  FROM check_ins ci
UNION ALL
SELECT so.member_id, so.placed_at, 'shop_order', so.id, 'Shop order ' || so.order_no || ' (' || so.channel || ')', so.total_amount
  FROM shop_orders so WHERE so.member_id IS NOT NULL
UNION ALL
SELECT bo.member_id, bo.placed_at, 'bar_order', bo.id, 'Bar order ' || bo.order_no, bo.total_amount
  FROM bar_orders bo WHERE bo.member_id IS NOT NULL
UNION ALL
SELECT ms.member_id, ms.start_date::timestamptz, 'membership', ms.id, p.name || ' (' || ms.status || ')', ms.fee_charged
  FROM memberships ms JOIN membership_plans p ON p.id = ms.plan_id;

-- Active memberships and days left (reminders / renewals list).
CREATE VIEW v_membership_expiry AS
SELECT m.id AS member_id, m.member_code, m.full_name, m.phone, p.name AS plan_name,
       ms.id AS membership_id, ms.end_date, (ms.end_date - current_date) AS days_left
  FROM memberships ms
  JOIN members m ON m.id = ms.member_id
  JOIN membership_plans p ON p.id = ms.plan_id
 WHERE ms.status = 'active';

-- Items at or below their reorder level (available = on hand - reserved).
CREATE VIEW v_low_stock AS
SELECT v.id AS variant_id, v.sku, p.name AS product_name, v.size, v.color,
       v.stock_on_hand, v.stock_reserved, (v.stock_on_hand - v.stock_reserved) AS available, v.reorder_level
  FROM product_variants v JOIN products p ON p.id = v.product_id
 WHERE v.is_active AND p.is_active AND (v.stock_on_hand - v.stock_reserved) <= v.reorder_level;

-- What the kitchen still has to make, and for whom.
CREATE VIEW v_kitchen_queue AS
SELECT oi.id AS item_id, o.order_no, t.table_number,
       COALESCE(m.full_name, g.full_name, tab.guest_name) AS ordered_for,
       oi.item_name, oi.quantity, oi.special_instructions, oi.kitchen_status, o.placed_at
  FROM bar_order_items oi
  JOIN bar_orders o ON o.id = oi.order_id
  LEFT JOIN dining_tables t ON t.id = o.table_id
  LEFT JOIN members m ON m.id = o.member_id
  LEFT JOIN guests g ON g.id = o.guest_id
  LEFT JOIN bar_tabs tab ON tab.id = o.tab_id
 WHERE oi.station = 'kitchen' AND oi.kitchen_status IN ('pending','preparing') AND o.status <> 'cancelled'
 ORDER BY o.placed_at;

-- Owner: earned, from where, per day. Roll up to week/month with date_trunc('week'|'month', revenue_date).
CREATE VIEW v_revenue_by_day_source AS
SELECT i.issue_date AS revenue_date, ii.source,
       SUM(ii.line_total - ii.tax_amount) AS net_revenue,
       SUM(ii.tax_amount)                 AS tax_collected,
       SUM(ii.line_total)                 AS gross_revenue
  FROM invoice_items ii JOIN invoices i ON i.id = ii.invoice_id
 WHERE i.status NOT IN ('draft','void')
 GROUP BY i.issue_date, ii.source;

-- Owner: money actually received, per day, by cash / card / UPI / online (refunds are in the refunds table).
CREATE VIEW v_payments_by_day_method AS
SELECT (p.paid_at AT TIME ZONE COALESCE((SELECT timezone FROM club_profile LIMIT 1), 'UTC'))::date AS payment_date,
       p.method, SUM(p.amount) AS amount_received, COUNT(*) AS payment_count
  FROM payments p
 WHERE p.status = 'success'
 GROUP BY 1, 2;

-- Owner: "what do we owe?"  suppliers/bills + approved salaries not yet paid + unpaid tax.
CREATE VIEW v_amounts_owed AS
SELECT 'bill'::text AS owed_type, COALESCE(s.name, ec.name) AS owed_to, e.description, e.amount AS amount_due, e.due_date
  FROM expenses e
  JOIN expense_categories ec ON ec.id = e.category_id
  LEFT JOIN suppliers s ON s.id = e.supplier_id
 WHERE e.status = 'unpaid'
UNION ALL
SELECT 'salary', emp.full_name, 'Salary ' || to_char(pr.period_month, 'Mon YYYY'), pi.net_pay, NULL::date
  FROM payroll_items pi
  JOIN payroll_runs pr ON pr.id = pi.payroll_run_id
  JOIN employees emp ON emp.id = pi.employee_id
 WHERE pi.payment_status = 'pending' AND pr.status IN ('approved','paid')
UNION ALL
SELECT 'tax', t.tax_type, 'Return for ' || t.period_start || ' to ' || t.period_end, t.net_payable, t.due_date
  FROM tax_returns t
 WHERE t.status <> 'paid' AND t.net_payable > 0;
