-- =====================================================================================
--  THE CHAMPIONS CLUB  -  Sports Club Management System
--  Database schema  |  PostgreSQL 14+  |  run top to bottom on an empty database
-- =====================================================================================
--
--  ROLES (decided)
--    1 owner        2 manager (exactly ONE)   3 front_desk (also handles enquiries)
--    4 shop_staff   5 bar_staff (bar, cafe, kitchen)   6 accountant
--    7 member (Gold / Silver / Junior are PLANS, not roles)   8 system_admin
--
--  SECTIONS
--    1  Identity & access     roles, permissions, role_permissions, users, user_roles
--    2  Club profile/settings club_profile, club_settings
--    3  Staff (HR)            employees, shift_templates, shifts, attendance_records,
--                             leave_types, leave_requests, payroll_runs, payroll_items
--    4  Members & customers   guardians, membership_plans, plan_benefits, members,
--                             memberships, guests, business_clients, member_notes
--    5  Courts & bookings     sports, courts, court_operating_hours, court_rates,
--                             court_reservations, bookings, check_ins
--    6  Tax                   tax_rates
--    7  Gear shop & stock     product_categories, products, product_variants, suppliers,
--                             purchase_orders, purchase_order_items, stock_movements,
--                             shop_orders, shop_order_items
--    8  Bar & cafeteria       bar_menu_categories, bar_menu_items, dining_tables,
--                             bar_tabs, bar_orders, bar_order_items
--    9  Enquiries (CRM)       enquiries, enquiry_activities, quotes, quote_items
--    10 Finance               invoices, invoice_items, payments, refunds, daily_closings,
--                             expense_categories, expenses, tax_returns, report_shares
--    11 Notifications & audit notifications, audit_logs
--    12-15 Triggers, indexes, seed data, reporting views, availability function
--
--  CONVENTIONS
--    * ids are bigint identity. Money is numeric(12,2). Percentages are numeric(5,2) (0-100).
--    * VARCHAR(255) + CHECK (...) is used instead of ENUM so allowed values are easy to edit.
--    * Unit prices are tax-EXCLUSIVE. invoice/order line_total = qty*unit_price - discount + tax.
--    * Snapshot columns (price, discount %, rate used) are copied at the time of sale so
--      later plan or price changes never rewrite history.
--    * day_of_week: 0 = Sunday ... 6 = Saturday (same as PostgreSQL EXTRACT(DOW)).
--    * Numbers such as invoice_no / order_no / booking_ref / member_code are generated by
--      the application; the database only guarantees they are unique.
--
--  KEY GUARANTEES ENFORCED BY THE DATABASE (not just the app)
--    * Two bookings can never overlap on the same court  (exclusion constraint, section 5)
--    * Max N bookings per member per day (default 2)     (trigger, setting in club_settings)
--    * Social-play sessions cannot exceed their capacity (trigger)
--    * Shop stock can never go negative; counter and online sales hit the same stock row
--    * Exactly one owner and one manager                 (unique indexes, section 1)
--    * A member cannot hold two overlapping memberships  (exclusion constraint, section 4)
--    * invoice.amount_paid / status follow the payments  (trigger, section 10)
--    * A payment can never be refunded for more than it was (trigger, section 10)
--
--  ASSUMPTIONS TO CONFIRM  (search for "ASSUMPTION" in this file)
--    A1 Juniors (under 18) need a guardian record.
--    A2 Both exclusive and social-play bookings count toward the 2-per-day limit.
--    A3 Prices are tax-exclusive; tax rates are GST-style placeholders.
--    A4 Currency INR, timezone Asia/Kolkata (UPI is mentioned in the statement).
--    A5 Sports list contains tennis, padel, badminton AND cricket because the problem
--       statement mentions both sets - keep only what the club offers.
-- =====================================================================================

   -- needed for the "no overlap" exclusion constraints




-- =====================================================================================
-- 1. IDENTITY & ACCESS
-- =====================================================================================

CREATE TABLE roles (
    id          smallint PRIMARY KEY,                 -- fixed ids, see seed data (section 14)
    code        VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE permissions (
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(255) NOT NULL UNIQUE,                 -- 'module.action', e.g. 'booking.manage'
    module      VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE role_permissions (
    role_id       smallint NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    permission_id bigint   NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- One login account per person: staff AND members who use the website/app.
CREATE TABLE users (
    id                   bigint AUTO_INCREMENT PRIMARY KEY,
    full_name            VARCHAR(255) NOT NULL,
    email                VARCHAR(255),
    phone                VARCHAR(255),
    password_hash        VARCHAR(255) NOT NULL,
    status               VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','disabled')),
    must_change_password boolean NOT NULL DEFAULT false,
    failed_login_count   smallint NOT NULL DEFAULT 0,
    locked_until         DATETIME,
    last_login_at        DATETIME,
    email_verified_at    DATETIME,
    phone_verified_at    DATETIME,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_contact_chk CHECK (email IS NOT NULL OR phone IS NOT NULL)
);
CREATE UNIQUE INDEX uq_users_email ON users (email);
CREATE UNIQUE INDEX uq_users_phone ON users (phone);

-- A user can hold more than one role (e.g. front_desk + accountant in a small club).
CREATE TABLE user_roles (
    user_id     bigint   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id     smallint NOT NULL REFERENCES roles(id),
    assigned_by bigint   REFERENCES users(id),
    assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);
-- Exactly one owner and exactly one manager (role ids 1 and 2).
-- To allow several managers later, just DROP INDEX uq_single_manager;




-- =====================================================================================
-- 2. CLUB PROFILE & SETTINGS   (feeds the public website and the booking rules)
-- =====================================================================================

CREATE TABLE club_profile (                           -- always exactly one row
    id            smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    name          VARCHAR(255) NOT NULL,
    tagline       VARCHAR(255),
    description   VARCHAR(255),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city          VARCHAR(255),
    state         VARCHAR(255),
    postal_code   VARCHAR(255),
    country       VARCHAR(255) NOT NULL DEFAULT 'IN',
    latitude      numeric(9,6),                        -- "find a place to play near me"
    longitude     numeric(9,6),
    phone         VARCHAR(255),
    email         VARCHAR(255),
    website_url   VARCHAR(255),
    logo_url      VARCHAR(255),
    tax_id        VARCHAR(255),                                -- GSTIN / VAT number printed on invoices
    currency_code char(3) NOT NULL DEFAULT 'INR',      -- ASSUMPTION A4
    timezone      VARCHAR(255) NOT NULL DEFAULT 'Asia/Kolkata',
    updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE club_settings (                          -- business rules the admin can change
    `key` VARCHAR(255) PRIMARY KEY,
    value       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    updated_by  bigint REFERENCES users(id),
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================================================
-- 3. STAFF (HR): employees, shifts, attendance, leave, payroll
-- =====================================================================================

CREATE TABLE employees (
    id                     bigint AUTO_INCREMENT PRIMARY KEY,
    employee_code          VARCHAR(255) NOT NULL UNIQUE,
    user_id                bigint UNIQUE REFERENCES users(id),   -- their login (NULL if none)
    full_name              VARCHAR(255) NOT NULL,
    phone                  VARCHAR(255) NOT NULL,
    email                  VARCHAR(255),
    date_of_birth          date,
    address                VARCHAR(255),
    emergency_contact_name  VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    department             VARCHAR(255) NOT NULL CHECK (department IN
                              ('management','front_desk','shop','bar','kitchen','finance','admin')),
    job_title              VARCHAR(255) NOT NULL,
    employment_type        VARCHAR(255) NOT NULL DEFAULT 'full_time'
                              CHECK (employment_type IN ('full_time','part_time','casual')),
    hire_date              date NOT NULL,
    termination_date       date,
    status                 VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','terminated')),
    reports_to_employee_id bigint REFERENCES employees(id),      -- leave/shift approver (the manager)
    pay_type               VARCHAR(255) NOT NULL DEFAULT 'monthly' CHECK (pay_type IN ('monthly','hourly')),
    base_salary            numeric(12,2) CHECK (base_salary >= 0),   -- per month
    hourly_rate            numeric(10,2) CHECK (hourly_rate >= 0),
    tax_id                 VARCHAR(255),                                 -- PAN etc., for tax deducted at source
    bank_account_holder    VARCHAR(255),
    bank_name              VARCHAR(255),
    bank_account_number    VARCHAR(255),                                 -- encrypt at application level
    bank_ifsc              VARCHAR(255),
    notes                  VARCHAR(255),
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (termination_date IS NULL OR termination_date >= hire_date),
    CHECK ((pay_type = 'monthly' AND base_salary IS NOT NULL) OR (pay_type = 'hourly' AND hourly_rate IS NOT NULL))
);

CREATE TABLE shift_templates (                        -- reusable patterns: Morning, Evening, Closing
    id         bigint AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    department VARCHAR(255) CHECK (department IN ('management','front_desk','shop','bar','kitchen','finance','admin')),
    start_time time NOT NULL,
    end_time   time NOT NULL,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE shifts (
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(id),
    department  VARCHAR(255) NOT NULL CHECK (department IN ('management','front_desk','shop','bar','kitchen','finance','admin')),
    template_id bigint REFERENCES shift_templates(id),
    starts_at   DATETIME NOT NULL,
    ends_at     DATETIME NOT NULL,
    status      VARCHAR(255) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','completed','absent','cancelled')),
    notes       VARCHAR(255),
    created_by  bigint REFERENCES users(id),
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (ends_at > starts_at)
);

CREATE TABLE attendance_records (                     -- actual clock-in / clock-out (feeds payroll)
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(id),
    shift_id    bigint REFERENCES shifts(id),
    clock_in    DATETIME NOT NULL,
    clock_out   DATETIME,
    method      VARCHAR(255) NOT NULL DEFAULT 'manual' CHECK (method IN ('manual','qr','biometric','app')),
    notes       VARCHAR(255),
    recorded_by bigint REFERENCES users(id),
    CHECK (clock_out IS NULL OR clock_out > clock_in)
);

CREATE TABLE leave_types (
    id                bigint AUTO_INCREMENT PRIMARY KEY,
    name              VARCHAR(255) NOT NULL UNIQUE,
    is_paid           boolean NOT NULL DEFAULT true,
    annual_quota_days numeric(4,1) CHECK (annual_quota_days >= 0),    -- NULL = not set / unlimited
    is_active         boolean NOT NULL DEFAULT true
);

CREATE TABLE leave_requests (
    id             bigint AUTO_INCREMENT PRIMARY KEY,
    employee_id    bigint NOT NULL REFERENCES employees(id),
    leave_type_id  bigint NOT NULL REFERENCES leave_types(id),
    start_date     date NOT NULL,
    end_date       date NOT NULL,
    days_requested numeric(4,1) NOT NULL CHECK (days_requested > 0),
    reason         VARCHAR(255),
    status         VARCHAR(255) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
    requested_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_by     bigint REFERENCES users(id),           -- the manager (or owner for the manager's own leave)
    decided_at     DATETIME,
    decision_note  VARCHAR(255),
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date),
    CHECK (status = 'pending' OR status = 'cancelled' OR decided_by IS NOT NULL)
);

CREATE TABLE payroll_runs (                           -- one run per month
    id           bigint AUTO_INCREMENT PRIMARY KEY,
    period_month date NOT NULL UNIQUE CHECK (extract(day FROM period_month) = 1),   -- first day of month
    status       VARCHAR(255) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','paid')),
    created_by   bigint REFERENCES users(id),
    approved_by  bigint REFERENCES users(id),
    approved_at  DATETIME,
    paid_at      DATETIME,
    notes        VARCHAR(255),
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payroll_items (                          -- one payslip per employee per run
    id                    bigint AUTO_INCREMENT PRIMARY KEY,
    payroll_run_id        bigint NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
    employee_id           bigint NOT NULL REFERENCES employees(id),
    days_worked           numeric(5,1) NOT NULL DEFAULT 0,
    hours_worked          numeric(7,2),
    unpaid_leave_days     numeric(4,1) NOT NULL DEFAULT 0,
    base_pay              numeric(12,2) NOT NULL DEFAULT 0 CHECK (base_pay >= 0),
    overtime_pay          numeric(12,2) NOT NULL DEFAULT 0 CHECK (overtime_pay >= 0),
    allowances            numeric(12,2) NOT NULL DEFAULT 0 CHECK (allowances >= 0),
    gross_pay             numeric(12,2) GENERATED ALWAYS AS (base_pay + overtime_pay + allowances) STORED,
    unpaid_leave_deduction numeric(12,2) NOT NULL DEFAULT 0 CHECK (unpaid_leave_deduction >= 0),
    tax_deducted          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_deducted >= 0),
    other_deductions      numeric(12,2) NOT NULL DEFAULT 0 CHECK (other_deductions >= 0),
    net_pay               numeric(12,2) GENERATED ALWAYS AS
                              (base_pay + overtime_pay + allowances
                               - unpaid_leave_deduction - tax_deducted - other_deductions) STORED,
    payment_status        VARCHAR(255) NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','paid')),
    paid_at               DATETIME,
    payment_method        VARCHAR(255) CHECK (payment_method IN ('cash','card','upi','online','bank_transfer','cheque')),
    payment_reference     VARCHAR(255),
    UNIQUE (payroll_run_id, employee_id)
);


-- =====================================================================================
-- 4. MEMBERS & CUSTOMERS
-- =====================================================================================

CREATE TABLE guardians (                              -- parent / guardian of a Junior member
    id           bigint AUTO_INCREMENT PRIMARY KEY,
    full_name    VARCHAR(255) NOT NULL,
    phone        VARCHAR(255) NOT NULL,
    email        VARCHAR(255),
    relationship VARCHAR(255),                                 -- mother, father, guardian...
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- The three tiers: Gold (premium, full access), Silver (standard), Junior (under 18, discounted).
CREATE TABLE membership_plans (
    id                    bigint AUTO_INCREMENT PRIMARY KEY,
    code                  VARCHAR(255) NOT NULL UNIQUE,         -- 'gold', 'silver', 'junior'
    name                  VARCHAR(255) NOT NULL,
    description           VARCHAR(255),
    fee                   numeric(10,2) NOT NULL CHECK (fee >= 0),
    duration_months       smallint NOT NULL CHECK (duration_months > 0),
    joining_fee           numeric(10,2) NOT NULL DEFAULT 0 CHECK (joining_fee >= 0),
    min_age               smallint CHECK (min_age >= 0),
    max_age               smallint,                     -- Junior: 17
    shop_discount_pct     numeric(5,2) NOT NULL DEFAULT 0 CHECK (shop_discount_pct BETWEEN 0 AND 100),
    bar_discount_pct      numeric(5,2) NOT NULL DEFAULT 0 CHECK (bar_discount_pct  BETWEEN 0 AND 100),
    can_join_social_play  boolean NOT NULL DEFAULT true,
    is_active             boolean NOT NULL DEFAULT true,
    sort_order            smallint NOT NULL DEFAULT 0,
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (min_age IS NULL OR max_age IS NULL OR max_age >= min_age)
);
-- Court prices per plan (free / discounted / walk-in) live in court_rates (section 5).

CREATE TABLE plan_benefits (                          -- bullet points for the website / plan comparison
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    plan_id     bigint NOT NULL REFERENCES membership_plans(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    sort_order  smallint NOT NULL DEFAULT 0
);

CREATE TABLE members (
    id                      bigint AUTO_INCREMENT PRIMARY KEY,
    member_code             VARCHAR(255) NOT NULL UNIQUE,        -- number on the card; what staff type at the desk
    qr_token                VARCHAR(255) NOT NULL UNIQUE DEFAULT (REPLACE(UUID(), '-', '')),
    user_id                 bigint UNIQUE REFERENCES users(id),   -- online login (NULL = desk-only member)
    full_name               VARCHAR(255) NOT NULL,
    date_of_birth           date NOT NULL ,
    phone                   VARCHAR(255) NOT NULL,
    email                   VARCHAR(255),
    address_line1           VARCHAR(255),
    address_line2           VARCHAR(255),
    city                    VARCHAR(255),
    postal_code             VARCHAR(255),
    photo_url               VARCHAR(255),                        -- so staff can recognise them quickly
    emergency_contact_name  VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    guardian_id             bigint REFERENCES guardians(id),
    status                  VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','left')),
    joined_on               date NOT NULL DEFAULT (CURDATE()),
    registered_by           bigint REFERENCES users(id), -- front-desk user who signed them up
    created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A member's plan over time. Renewal, upgrade, downgrade = a NEW row linked to the previous one.
CREATE TABLE memberships (
    id                     bigint AUTO_INCREMENT PRIMARY KEY,
    member_id              bigint NOT NULL REFERENCES members(id),
    plan_id                bigint NOT NULL REFERENCES membership_plans(id),
    start_date             date NOT NULL,
    end_date               date NOT NULL,               -- expiry; reminders are driven by this
    status                 VARCHAR(255) NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending','active','expired','cancelled','changed')),
                           -- 'changed' = replaced by a different plan before its end date
    started_as             VARCHAR(255) NOT NULL DEFAULT 'new' CHECK (started_as IN ('new','renewal','upgrade','downgrade')),
    previous_membership_id bigint REFERENCES memberships(id),
    auto_renew             boolean NOT NULL DEFAULT false,
    fee_charged            numeric(10,2) NOT NULL CHECK (fee_charged >= 0),        -- snapshot of plan fee
    joining_fee_charged    numeric(10,2) NOT NULL DEFAULT 0 CHECK (joining_fee_charged >= 0),
    cancelled_at           DATETIME,
    cancelled_by           bigint REFERENCES users(id),
    cancellation_reason    VARCHAR(255),
    created_by             bigint REFERENCES users(id),
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date)
);

CREATE TABLE guests (                                 -- walk-ins / non-members who pay the walk-in rate
    id                  bigint AUTO_INCREMENT PRIMARY KEY,
    full_name           VARCHAR(255) NOT NULL,
    phone               VARCHAR(255),
    email               VARCHAR(255),
    source              VARCHAR(255) NOT NULL DEFAULT 'walk_in' CHECK (source IN ('walk_in','phone','website','bar')),
    converted_member_id bigint REFERENCES members(id),   -- set when a guest later joins
    notes               VARCHAR(255),
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_clients (                       -- companies the club invoices
    id                  bigint AUTO_INCREMENT PRIMARY KEY,
    company_name        VARCHAR(255) NOT NULL,
    contact_person      VARCHAR(255),
    email               VARCHAR(255),
    phone               VARCHAR(255),
    billing_address1    VARCHAR(255),
    billing_address2    VARCHAR(255),
    city                VARCHAR(255),
    state               VARCHAR(255),
    postal_code         VARCHAR(255),
    tax_id              VARCHAR(255),                          -- client GSTIN
    payment_terms_days  smallint NOT NULL DEFAULT 15 CHECK (payment_terms_days >= 0),
    status              VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
    notes               VARCHAR(255),
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member_notes (                           -- staff notes shown on the member's profile
    id         bigint AUTO_INCREMENT PRIMARY KEY,
    member_id  bigint NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    note       VARCHAR(255) NOT NULL,
    is_pinned  boolean NOT NULL DEFAULT false,
    created_by bigint NOT NULL REFERENCES users(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================================================
-- 5. COURTS & BOOKINGS
-- =====================================================================================

CREATE TABLE sports (
    id        bigint AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE courts (
    id                    bigint AUTO_INCREMENT PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL UNIQUE,         -- 'Court 1', 'Padel A'
    sport_id              bigint NOT NULL REFERENCES sports(id),
    surface               VARCHAR(255),                         -- clay, hard, synthetic, turf...
    is_indoor             boolean NOT NULL DEFAULT false,
    social_play_capacity  smallint CHECK (social_play_capacity > 0),   -- default people per court in social play
    status                VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','maintenance','closed')),
    notes                 VARCHAR(255),
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE court_operating_hours (                  -- when each court can be booked
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    court_id    bigint NOT NULL REFERENCES courts(id) ON DELETE CASCADE,
    day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    open_time   time NOT NULL,
    close_time  time NOT NULL,
    UNIQUE (court_id, day_of_week),
    CHECK (close_time > open_time)
);

-- Price list. plan_id NULL = walk-in / non-member rate. price 0 = free (e.g. Gold).
CREATE TABLE court_rates (
    id           bigint AUTO_INCREMENT PRIMARY KEY,
    sport_id     bigint NOT NULL REFERENCES sports(id),
    plan_id      bigint REFERENCES membership_plans(id),
    applies_to   VARCHAR(255) NOT NULL DEFAULT 'exclusive_booking'
                    CHECK (applies_to IN ('exclusive_booking','social_play_per_person')),
    days_of_week JSON ,
    start_time   time,                                  -- optional peak / off-peak band
    end_time     time,
    price        numeric(10,2) NOT NULL CHECK (price >= 0),   -- per session (or per person for social play)
    valid_from   date NOT NULL DEFAULT (CURDATE()),
    valid_to     date,
    is_active    boolean NOT NULL DEFAULT true,
    CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CHECK ((start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL))
);

-- The physical occupancy of a court. THIS is what must never overlap.
--   exclusive : one booking owns the court for the session
--   social    : many people share the court (Friday-night social play)
--   blocked   : maintenance, tournament, private hire
CREATE TABLE court_reservations (
    id               bigint AUTO_INCREMENT PRIMARY KEY,
    court_id         bigint NOT NULL REFERENCES courts(id),
    starts_at        DATETIME NOT NULL,
    ends_at          DATETIME NOT NULL,
    reservation_type VARCHAR(255) NOT NULL CHECK (reservation_type IN ('exclusive','social','blocked')),
    status           VARCHAR(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','cancelled')),
    social_title     VARCHAR(255),                              -- 'Friday Night Social'
    social_capacity  smallint CHECK (social_capacity > 0),
    block_reason     VARCHAR(255),
    created_by       bigint REFERENCES users(id),
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (ends_at > starts_at),
    CHECK ((reservation_type = 'social' AND social_capacity IS NOT NULL) OR (reservation_type != 'social' AND social_capacity IS NULL)),
    UNIQUE (id, reservation_type)
);

-- A person's booking on a reservation. Exclusive reservation = one booking; social = many.
CREATE TABLE bookings (
    id                bigint AUTO_INCREMENT PRIMARY KEY,
    booking_ref       VARCHAR(255) NOT NULL UNIQUE,
    reservation_id    bigint NOT NULL,
    reservation_type  VARCHAR(255) NOT NULL CHECK (reservation_type IN ('exclusive','social')),
    member_id         bigint REFERENCES members(id),
    guest_id          bigint REFERENCES guests(id),
    membership_id     bigint REFERENCES memberships(id),   -- the plan in force when booked
    booked_via        VARCHAR(255) NOT NULL CHECK (booked_via IN ('member_app','website','front_desk','phone','walk_in')),
    booked_by         bigint REFERENCES users(id),         -- who made it (member, receptionist; NULL for public visitor)
    is_trial          boolean NOT NULL DEFAULT false,      -- trial session booked from the website
    rate_id           bigint REFERENCES court_rates(id),
    price_basis       VARCHAR(255) NOT NULL DEFAULT 'walk_in_rate'
                         CHECK (price_basis IN ('member_rate','walk_in_rate','plan_included','trial','complimentary')),
    amount_charged    numeric(10,2) NOT NULL DEFAULT 0 CHECK (amount_charged >= 0),   -- 0 = free for this plan
    status            VARCHAR(255) NOT NULL DEFAULT 'confirmed'
                         CHECK (status IN ('confirmed','checked_in','completed','cancelled','no_show')),
    checked_in_at     DATETIME,
    cancelled_at      DATETIME,
    cancelled_by      bigint REFERENCES users(id),
    cancellation_reason VARCHAR(255),
    notes             VARCHAR(255),
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (((member_id IS NOT NULL) + (guest_id IS NOT NULL)) = 1),
    FOREIGN KEY (reservation_id, reservation_type) REFERENCES court_reservations (id, reservation_type)
);
-- an exclusive reservation can have only one live booking
CREATE UNIQUE INDEX uq_one_live_exclusive_booking
    ON bookings (reservation_id);
-- a person cannot join the same social session twice
CREATE UNIQUE INDEX uq_social_member_once
    ON bookings (reservation_id, member_id);
CREATE UNIQUE INDEX uq_social_guest_once
    ON bookings (reservation_id, guest_id);

CREATE TABLE check_ins (                              -- every time a member turns up
    id            bigint AUTO_INCREMENT PRIMARY KEY,
    member_id     bigint NOT NULL REFERENCES members(id),
    booking_id    bigint REFERENCES bookings(id),
    checked_in_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    method        VARCHAR(255) NOT NULL DEFAULT 'member_code' CHECK (method IN ('qr','member_code','name_search','phone')),
    recorded_by   bigint REFERENCES users(id),
    notes         VARCHAR(255)
);

-- Booking rules enforced in the database -------------------------------------------------




-- When an exclusive booking is cancelled, free the court straight away.





-- =====================================================================================
-- 6. TAX
-- =====================================================================================

CREATE TABLE tax_rates (
    id        bigint AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,                     -- 'GST 18%'
    rate_pct  numeric(5,2) NOT NULL CHECK (rate_pct BETWEEN 0 AND 100),
    is_active boolean NOT NULL DEFAULT true
);


-- =====================================================================================
-- 7. GEAR SHOP & STOCK   (counter sales and online orders share the same stock)
-- =====================================================================================

CREATE TABLE product_categories (
    id         bigint AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,                    -- rackets, balls, shoes, accessories, apparel
    parent_id  bigint REFERENCES product_categories(id),
    sort_order smallint NOT NULL DEFAULT 0,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE products (
    id               bigint AUTO_INCREMENT PRIMARY KEY,
    category_id      bigint NOT NULL REFERENCES product_categories(id),
    name             VARCHAR(255) NOT NULL,
    brand            VARCHAR(255),
    description      VARCHAR(255),
    base_price       numeric(12,2) NOT NULL CHECK (base_price >= 0),     -- selling price, before tax
    cost_price       numeric(12,2) CHECK (cost_price >= 0),
    tax_rate_id      bigint NOT NULL REFERENCES tax_rates(id),
    image_url        VARCHAR(255),
    is_listed_online boolean NOT NULL DEFAULT true,      -- visible on the website / member app
    is_active        boolean NOT NULL DEFAULT true,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Stock is held per variant (shoe size, colour...). A product with no options still has one variant.
CREATE TABLE product_variants (
    id             bigint AUTO_INCREMENT PRIMARY KEY,
    product_id     bigint NOT NULL REFERENCES products(id),
    sku            VARCHAR(255) NOT NULL UNIQUE,
    barcode        VARCHAR(255) UNIQUE,
    size           VARCHAR(255),
    color          VARCHAR(255),
    price_override numeric(12,2) CHECK (price_override >= 0),            -- NULL = use products.base_price
    stock_on_hand  integer NOT NULL DEFAULT 0 CHECK (stock_on_hand >= 0),  -- physically on the shelf
    stock_reserved integer NOT NULL DEFAULT 0 CHECK (stock_reserved >= 0), -- held for online orders awaiting pickup
    reorder_level  integer NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),  -- low-stock alert threshold
    is_active      boolean NOT NULL DEFAULT true,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- available to sell = stock_on_hand - stock_reserved   (see view v_low_stock)

CREATE TABLE suppliers (
    id                 bigint AUTO_INCREMENT PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    contact_person     VARCHAR(255),
    phone              VARCHAR(255),
    email              VARCHAR(255),
    address            VARCHAR(255),
    tax_id             VARCHAR(255),
    payment_terms_days smallint NOT NULL DEFAULT 30 CHECK (payment_terms_days >= 0),
    is_active          boolean NOT NULL DEFAULT true,
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_orders (                        -- restocking from a supplier
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    po_number   VARCHAR(255) NOT NULL UNIQUE,
    supplier_id bigint NOT NULL REFERENCES suppliers(id),
    status      VARCHAR(255) NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft','ordered','partially_received','received','cancelled')),
    ordered_at  DATETIME,
    expected_on date,
    received_at DATETIME,
    notes       VARCHAR(255),
    created_by  bigint REFERENCES users(id),
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_order_items (
    id                bigint AUTO_INCREMENT PRIMARY KEY,
    purchase_order_id bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    variant_id        bigint NOT NULL REFERENCES product_variants(id),
    quantity_ordered  integer NOT NULL CHECK (quantity_ordered > 0),
    quantity_received integer NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    unit_cost         numeric(12,2) NOT NULL CHECK (unit_cost >= 0),
    line_total        numeric(12,2) GENERATED ALWAYS AS (quantity_ordered * unit_cost) STORED
);

-- Stock ledger: every change to stock_on_hand is a row here; the trigger below updates the variant.
CREATE TABLE stock_movements (
    id              bigint AUTO_INCREMENT PRIMARY KEY,
    variant_id      bigint NOT NULL REFERENCES product_variants(id),
    quantity_change integer NOT NULL CHECK (quantity_change <> 0),      -- + in, - out
    reason          VARCHAR(255) NOT NULL CHECK (reason IN
                       ('opening_stock','purchase_received','sale','return','adjustment','damaged','lost')),
    reference_type  VARCHAR(255) CHECK (reference_type IN ('shop_order','purchase_order')),
    reference_id    bigint,
    balance_after   integer,                                            -- filled by the trigger
    notes           VARCHAR(255),
    performed_by    bigint REFERENCES users(id),
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);





-- Counter sale and online order are the SAME table, told apart by channel.
CREATE TABLE shop_orders (
    id                     bigint AUTO_INCREMENT PRIMARY KEY,
    order_no               VARCHAR(255) NOT NULL UNIQUE,
    member_id              bigint REFERENCES members(id),
    guest_id               bigint REFERENCES guests(id),               -- both NULL = anonymous counter sale
    channel                VARCHAR(255) NOT NULL CHECK (channel IN ('counter','online')),
    fulfillment_type       VARCHAR(255) NOT NULL CHECK (fulfillment_type IN ('in_store','pickup','delivery')),
    status                 VARCHAR(255) NOT NULL DEFAULT 'pending' CHECK (status IN
                              ('pending','confirmed','ready_for_pickup','out_for_delivery','completed','cancelled')),
    taken_by               bigint REFERENCES users(id),                -- staff who rang it up (counter)
    member_discount_pct    numeric(5,2) NOT NULL DEFAULT 0 CHECK (member_discount_pct BETWEEN 0 AND 100), -- snapshot of plan discount
    subtotal               numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total         numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total              numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    delivery_fee           numeric(10,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    total_amount           numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    delivery_address_line1 VARCHAR(255),
    delivery_address_line2 VARCHAR(255),
    delivery_city          VARCHAR(255),
    delivery_postal_code   VARCHAR(255),
    delivery_phone         VARCHAR(255),
    delivery_notes         VARCHAR(255),
    assigned_delivery_to   bigint REFERENCES employees(id),
    placed_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at               DATETIME,
    completed_at           DATETIME,
    cancelled_at           DATETIME,
    cancellation_reason    VARCHAR(255),
    notes                  VARCHAR(255),
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (((member_id IS NOT NULL) + (guest_id IS NOT NULL)) <= 1),
    CHECK (channel = 'online' OR fulfillment_type = 'in_store'),
    CHECK (channel = 'counter' OR fulfillment_type <> 'in_store'),
    CHECK (fulfillment_type <> 'delivery' OR delivery_address_line1 IS NOT NULL),
    CHECK (channel = 'online' OR member_id IS NOT NULL OR guest_id IS NOT NULL OR taken_by IS NOT NULL)
);

CREATE TABLE shop_order_items (
    id              bigint AUTO_INCREMENT PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    variant_id      bigint NOT NULL REFERENCES product_variants(id),
    product_name    VARCHAR(255) NOT NULL,                       -- snapshot (name + size/colour)
    quantity        integer NOT NULL CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0)
);


-- =====================================================================================
-- 8. BAR & CAFETERIA
-- =====================================================================================

CREATE TABLE bar_menu_categories (                    -- drinks, snacks, meals
    id         bigint AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    sort_order smallint NOT NULL DEFAULT 0,
    is_active  boolean NOT NULL DEFAULT true
);

CREATE TABLE bar_menu_items (
    id           bigint AUTO_INCREMENT PRIMARY KEY,
    category_id  bigint NOT NULL REFERENCES bar_menu_categories(id),
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    price        numeric(10,2) NOT NULL CHECK (price >= 0),          -- before tax
    tax_rate_id  bigint NOT NULL REFERENCES tax_rates(id),
    station      VARCHAR(255) NOT NULL DEFAULT 'bar' CHECK (station IN ('bar','kitchen')),   -- who prepares it
    is_available boolean NOT NULL DEFAULT true,           -- flip off when sold out
    is_active    boolean NOT NULL DEFAULT true,
    image_url    VARCHAR(255),
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dining_tables (
    id           bigint AUTO_INCREMENT PRIMARY KEY,
    table_number VARCHAR(255) NOT NULL UNIQUE,
    seats        smallint NOT NULL CHECK (seats > 0),
    zone         VARCHAR(255),                                   -- indoor, terrace, courtside
    status       VARCHAR(255) NOT NULL DEFAULT 'available' CHECK (status IN ('available','occupied','reserved','out_of_service'))
);

-- A tab = several orders settled together ("run a tab and pay before they leave").
CREATE TABLE bar_tabs (
    id         bigint AUTO_INCREMENT PRIMARY KEY,
    tab_no     VARCHAR(255) NOT NULL UNIQUE,
    member_id  bigint REFERENCES members(id),
    guest_id   bigint REFERENCES guests(id),
    guest_name VARCHAR(255),                                     -- quick label for an unregistered guest
    table_id   bigint REFERENCES dining_tables(id),
    status     VARCHAR(255) NOT NULL DEFAULT 'open' CHECK (status IN ('open','settled','void')),
    opened_by  bigint NOT NULL REFERENCES users(id),
    opened_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at DATETIME,
    closed_by  bigint REFERENCES users(id),
    CHECK (((member_id IS NOT NULL) + (guest_id IS NOT NULL)) <= 1)
);

CREATE TABLE bar_orders (
    id                  bigint AUTO_INCREMENT PRIMARY KEY,
    order_no            VARCHAR(255) NOT NULL UNIQUE,
    tab_id              bigint REFERENCES bar_tabs(id),
    table_id            bigint REFERENCES dining_tables(id),
    member_id           bigint REFERENCES members(id),
    guest_id            bigint REFERENCES guests(id),
    taken_by            bigint NOT NULL REFERENCES users(id),        -- the staff member on shift
    status              VARCHAR(255) NOT NULL DEFAULT 'placed'
                           CHECK (status IN ('placed','preparing','ready','served','cancelled')),
    member_discount_pct numeric(5,2) NOT NULL DEFAULT 0 CHECK (member_discount_pct BETWEEN 0 AND 100),  -- applied automatically
    subtotal            numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total      numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total           numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount        numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes               VARCHAR(255),
    placed_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    served_at           DATETIME,
    cancelled_at        DATETIME,
    cancellation_reason VARCHAR(255),
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (((member_id IS NOT NULL) + (guest_id IS NOT NULL)) <= 1)
);

CREATE TABLE bar_order_items (
    id                   bigint AUTO_INCREMENT PRIMARY KEY,
    order_id             bigint NOT NULL REFERENCES bar_orders(id) ON DELETE CASCADE,
    menu_item_id         bigint NOT NULL REFERENCES bar_menu_items(id),
    item_name            VARCHAR(255) NOT NULL,                  -- snapshot
    quantity             integer NOT NULL CHECK (quantity > 0),
    unit_price           numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount      numeric(10,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id          bigint REFERENCES tax_rates(id),
    tax_amount           numeric(10,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total           numeric(10,2) NOT NULL CHECK (line_total >= 0),
    station              VARCHAR(255) NOT NULL CHECK (station IN ('bar','kitchen')),
    kitchen_status       VARCHAR(255) NOT NULL DEFAULT 'pending'
                            CHECK (kitchen_status IN ('pending','preparing','ready','served','cancelled')),
    special_instructions VARCHAR(255),
    ready_at             DATETIME
);


-- =====================================================================================
-- 9. ENQUIRIES (CRM)   handled by the receptionist
-- =====================================================================================

CREATE TABLE enquiries (
    id                  bigint AUTO_INCREMENT PRIMARY KEY,
    full_name           VARCHAR(255) NOT NULL,
    company_name        VARCHAR(255),                              -- for corporate enquiries
    phone               VARCHAR(255),
    email               VARCHAR(255),
    source              VARCHAR(255) NOT NULL DEFAULT 'website_form'
                           CHECK (source IN ('website_form','trial_booking','phone','walk_in','email','referral','other')),
    enquiry_type        VARCHAR(255) NOT NULL DEFAULT 'membership'
                           CHECK (enquiry_type IN ('membership','trial_session','court_booking','shop','corporate','general')),
    interested_plan_id  bigint REFERENCES membership_plans(id),
    interested_sport_id bigint REFERENCES sports(id),
    message             VARCHAR(255),
    status              VARCHAR(255) NOT NULL DEFAULT 'new'
                           CHECK (status IN ('new','contacted','quoted','trial_scheduled','won','lost')),
    assigned_to         bigint REFERENCES users(id),       -- the receptionist following it up
    next_follow_up_at   DATETIME,
    trial_booking_id    bigint REFERENCES bookings(id),
    converted_member_id bigint REFERENCES members(id),     -- set when they join
    business_client_id  bigint REFERENCES business_clients(id),
    lost_reason         VARCHAR(255),
    closed_at           DATETIME,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (phone IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE enquiry_activities (                      -- follow-up trail so nothing "vanishes"
    id            bigint AUTO_INCREMENT PRIMARY KEY,
    enquiry_id    bigint NOT NULL REFERENCES enquiries(id) ON DELETE CASCADE,
    activity_type VARCHAR(255) NOT NULL CHECK (activity_type IN
                     ('note','call','email','sms','whatsapp','visit','status_change','quote_sent')),
    summary       VARCHAR(255) NOT NULL,
    performed_by  bigint REFERENCES users(id),
    occurred_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quotes (
    id                 bigint AUTO_INCREMENT PRIMARY KEY,
    quote_no           VARCHAR(255) NOT NULL UNIQUE,
    enquiry_id         bigint NOT NULL REFERENCES enquiries(id),
    plan_id            bigint REFERENCES membership_plans(id),
    business_client_id bigint REFERENCES business_clients(id),
    status             VARCHAR(255) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','accepted','rejected','expired')),
    valid_until        date,
    subtotal           numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total     numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount       numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    sent_at            DATETIME,
    sent_via           VARCHAR(255) CHECK (sent_via IN ('email','whatsapp','sms','print')),
    accepted_at        DATETIME,
    notes              VARCHAR(255),
    created_by         bigint REFERENCES users(id),
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quote_items (
    id              bigint AUTO_INCREMENT PRIMARY KEY,
    quote_id        bigint NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
    description     VARCHAR(255) NOT NULL,
    quantity        numeric(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0)
);


-- =====================================================================================
-- 10. FINANCE
-- =====================================================================================

-- One invoice table for everything: counter receipts, bar bills, court fees, memberships,
-- and invoices to business clients. Each LINE says which part of the club earned it.
CREATE TABLE invoices (
    id                 bigint AUTO_INCREMENT PRIMARY KEY,
    invoice_no         VARCHAR(255) NOT NULL UNIQUE,
    member_id          bigint REFERENCES members(id),
    guest_id           bigint REFERENCES guests(id),
    business_client_id bigint REFERENCES business_clients(id),
    bill_to_name       VARCHAR(255),                              -- snapshot name printed on the invoice
    quote_id           bigint REFERENCES quotes(id),
    status             VARCHAR(255) NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft','issued','partially_paid','paid','void')),
    issue_date         date NOT NULL DEFAULT (CURDATE()),
    due_date           date,                              -- overdue = issued/partially_paid and due_date < today
    subtotal           numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_total     numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    tax_total          numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total_amount       numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    amount_paid        numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),   -- kept in sync by trigger
    balance_due        numeric(12,2) GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
    notes              VARCHAR(255),
    issued_by          bigint REFERENCES users(id),
    voided_at          DATETIME,
    voided_by          bigint REFERENCES users(id),
    void_reason        VARCHAR(255),
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (((member_id IS NOT NULL) + (guest_id IS NOT NULL) + (business_client_id IS NOT NULL)) <= 1)
);

CREATE TABLE invoice_items (
    id              bigint AUTO_INCREMENT PRIMARY KEY,
    invoice_id      bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    source          VARCHAR(255) NOT NULL CHECK (source IN ('membership','court_booking','shop','bar','other')),  -- "from where"
    description     VARCHAR(255) NOT NULL,
    quantity        numeric(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    discount_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_rate_id     bigint REFERENCES tax_rates(id),
    tax_amount      numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total      numeric(12,2) NOT NULL CHECK (line_total >= 0),       -- includes tax
    -- what this line bills (at most one):
    membership_id   bigint REFERENCES memberships(id),
    booking_id      bigint REFERENCES bookings(id),
    shop_order_id   bigint REFERENCES shop_orders(id),
    bar_order_id    bigint REFERENCES bar_orders(id),                     -- a tab settles as one line per order
    CHECK (((membership_id IS NOT NULL) + (booking_id IS NOT NULL) + (shop_order_id IS NOT NULL) + (bar_order_id IS NOT NULL)) <= 1),
    CHECK (membership_id IS NULL OR source = 'membership'),
    CHECK (booking_id    IS NULL OR source = 'court_booking'),
    CHECK (shop_order_id IS NULL OR source = 'shop'),
    CHECK (bar_order_id  IS NULL OR source = 'bar')
);

CREATE TABLE payments (
    id             bigint AUTO_INCREMENT PRIMARY KEY,
    receipt_no     VARCHAR(255) UNIQUE,
    invoice_id     bigint NOT NULL REFERENCES invoices(id),
    amount         numeric(12,2) NOT NULL CHECK (amount > 0),
    method         VARCHAR(255) NOT NULL CHECK (method IN ('cash','card','upi','online','bank_transfer','cheque')),
    status         VARCHAR(255) NOT NULL DEFAULT 'success' CHECK (status IN ('pending','success','failed')),
    gateway_name   VARCHAR(255),                                  -- Razorpay, Stripe... for online payments
    transaction_ref VARCHAR(255),                                 -- UPI ref / card auth / gateway txn id
    card_last4     char(4),
    received_by    bigint REFERENCES users(id),           -- NULL for online self-payments
    paid_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes          VARCHAR(255),
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Payments are never deleted; corrections are made with refunds.

CREATE TABLE refunds (                                  -- e.g. cancelled booking, returned goods
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    payment_id  bigint NOT NULL REFERENCES payments(id),
    amount      numeric(12,2) NOT NULL CHECK (amount > 0),
    method      VARCHAR(255) NOT NULL CHECK (method IN ('cash','card','upi','online','bank_transfer','cheque')),
    reason      VARCHAR(255),
    refunded_by bigint NOT NULL REFERENCES users(id),
    refunded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A payment can never be refunded for more than it was.




-- Keep invoices.amount_paid and invoices.status in line with payments and refunds.










-- End-of-day cash-up per department ("what did the bar actually earn today?").
CREATE TABLE daily_closings (
    id            bigint AUTO_INCREMENT PRIMARY KEY,
    business_date date NOT NULL,
    department    VARCHAR(255) NOT NULL CHECK (department IN ('courts','shop','bar','all')),
    total_sales   numeric(12,2) NOT NULL DEFAULT 0,
    cash_total    numeric(12,2) NOT NULL DEFAULT 0,
    card_total    numeric(12,2) NOT NULL DEFAULT 0,
    upi_total     numeric(12,2) NOT NULL DEFAULT 0,
    online_total  numeric(12,2) NOT NULL DEFAULT 0,
    other_total   numeric(12,2) NOT NULL DEFAULT 0,
    opening_cash  numeric(12,2) NOT NULL DEFAULT 0,
    expected_cash numeric(12,2) NOT NULL DEFAULT 0,       -- opening cash + cash sales - cash refunds
    counted_cash  numeric(12,2) NOT NULL DEFAULT 0,
    cash_variance numeric(12,2) GENERATED ALWAYS AS (counted_cash - expected_cash) STORED,
    closed_by     bigint NOT NULL REFERENCES users(id),
    closed_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes         VARCHAR(255),
    UNIQUE (business_date, department)
);

CREATE TABLE expense_categories (
    id        bigint AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

-- Money going out (supplier bills, rent, utilities...). status 'unpaid' = something we owe.
CREATE TABLE expenses (
    id                bigint AUTO_INCREMENT PRIMARY KEY,
    category_id       bigint NOT NULL REFERENCES expense_categories(id),
    supplier_id       bigint REFERENCES suppliers(id),
    purchase_order_id bigint REFERENCES purchase_orders(id),
    description       VARCHAR(255) NOT NULL,
    amount            numeric(12,2) NOT NULL CHECK (amount > 0),       -- total including tax
    tax_amount        numeric(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),   -- input tax, for tax returns
    expense_date      date NOT NULL DEFAULT (CURDATE()),
    due_date          date,
    status            VARCHAR(255) NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid','paid','void')),
    paid_at           DATETIME,
    payment_method    VARCHAR(255) CHECK (payment_method IN ('cash','card','upi','online','bank_transfer','cheque')),
    reference_no      VARCHAR(255),
    receipt_url       VARCHAR(255),
    recorded_by       bigint REFERENCES users(id),
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status <> 'paid' OR paid_at IS NOT NULL)
);

CREATE TABLE tax_returns (                              -- "taxes to report"
    id                 bigint AUTO_INCREMENT PRIMARY KEY,
    tax_type           VARCHAR(255) NOT NULL,                   -- 'GST', 'TDS', 'Income tax'...
    period_start       date NOT NULL,
    period_end         date NOT NULL,
    tax_collected      numeric(12,2) NOT NULL DEFAULT 0,   -- on sales
    tax_credit         numeric(12,2) NOT NULL DEFAULT 0,   -- on purchases / expenses
    net_payable        numeric(12,2) GENERATED ALWAYS AS (tax_collected - tax_credit) STORED,
    status             VARCHAR(255) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','filed','paid')),
    due_date           date,
    filed_at           DATETIME,
    filed_by           bigint REFERENCES users(id),
    paid_at            DATETIME,
    reference_no       VARCHAR(255),
    notes              VARCHAR(255),
    created_by         bigint REFERENCES users(id),
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (period_end >= period_start)
);

CREATE TABLE report_shares (                            -- owner shares "the numbers" with a partner, bank, accountant
    id              bigint AUTO_INCREMENT PRIMARY KEY,
    report_type     VARCHAR(255) NOT NULL CHECK (report_type IN
                       ('daily_summary','weekly_summary','monthly_summary','revenue_by_source','payables','tax_summary','custom')),
    period_start    date NOT NULL,
    period_end      date NOT NULL,
    snapshot        JSON NOT NULL,                      -- the figures frozen at the moment of sharing
    share_token     VARCHAR(255) NOT NULL UNIQUE DEFAULT (REPLACE(UUID(), '-', '')),
    recipient_name  VARCHAR(255),
    recipient_email VARCHAR(255),
    expires_at      DATETIME,
    revoked_at      DATETIME,
    view_count      integer NOT NULL DEFAULT 0,
    created_by      bigint NOT NULL REFERENCES users(id),
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (period_end >= period_start)
);


-- =====================================================================================
-- 11. NOTIFICATIONS & AUDIT
-- =====================================================================================

CREATE TABLE notifications (
    id                bigint AUTO_INCREMENT PRIMARY KEY,
    recipient_user_id bigint REFERENCES users(id),
    recipient_contact VARCHAR(255),                              -- email / phone for someone without a login
    type              VARCHAR(255) NOT NULL,                     -- enquiry_new, membership_expiring, low_stock,
                                                         -- leave_requested, leave_decided, order_ready, booking_confirmed...
    channel           VARCHAR(255) NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app','email','sms','whatsapp','push')),
    title             VARCHAR(255) NOT NULL,
    body              VARCHAR(255),
    entity_type       VARCHAR(255),                              -- what it is about, e.g. 'membership'
    entity_id         bigint,
    dedupe_key        VARCHAR(255) UNIQUE,                       -- e.g. 'membership_expiry:42:7d' so a reminder is sent once
    status            VARCHAR(255) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
    is_read           boolean NOT NULL DEFAULT false,
    read_at           DATETIME,
    scheduled_for     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at           DATETIME,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (recipient_user_id IS NOT NULL OR recipient_contact IS NOT NULL)
);

CREATE TABLE audit_logs (                               -- who changed what (money, prices, roles, stock)
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    user_id     bigint REFERENCES users(id),
    action      VARCHAR(255) NOT NULL,                           -- 'create', 'update', 'delete', 'login', 'refund', 'void'...
    entity_type VARCHAR(255) NOT NULL,
    entity_id   bigint,
    old_values  JSON,
    new_values  JSON,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(255),
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================================================
-- 12. updated_at TRIGGERS  (every table that has an updated_at column)
-- =====================================================================================




-- =====================================================================================
-- 13. INDEXES  (exclusion constraints and UNIQUE columns already have their own)
-- =====================================================================================

CREATE INDEX idx_user_roles_role          ON user_roles (role_id);
CREATE INDEX idx_members_phone            ON members (phone);
CREATE INDEX idx_members_name             ON members (full_name);
CREATE INDEX idx_memberships_member       ON memberships (member_id, status);
CREATE INDEX idx_memberships_expiry       ON memberships (end_date);
CREATE INDEX idx_guests_phone             ON guests (phone);
CREATE INDEX idx_member_notes_member      ON member_notes (member_id);
CREATE INDEX idx_court_res_start          ON court_reservations (starts_at);
CREATE INDEX idx_bookings_member          ON bookings (member_id, status);
CREATE INDEX idx_bookings_guest           ON bookings (guest_id);
CREATE INDEX idx_bookings_reservation     ON bookings (reservation_id);
CREATE INDEX idx_checkins_member          ON check_ins (member_id, checked_in_at DESC);
CREATE INDEX idx_court_rates_lookup       ON court_rates (sport_id, plan_id, applies_to);
CREATE INDEX idx_products_category        ON products (category_id);
CREATE INDEX idx_variants_product         ON product_variants (product_id);
CREATE INDEX idx_stock_mv_variant         ON stock_movements (variant_id, created_at DESC);
CREATE INDEX idx_shop_orders_member       ON shop_orders (member_id, placed_at DESC);
CREATE INDEX idx_shop_orders_status       ON shop_orders (status);
CREATE INDEX idx_shop_items_order         ON shop_order_items (order_id);
CREATE INDEX idx_bar_tabs_open            ON bar_tabs (status);
CREATE INDEX idx_bar_orders_tab           ON bar_orders (tab_id);
CREATE INDEX idx_bar_orders_member        ON bar_orders (member_id, placed_at DESC);
CREATE INDEX idx_bar_orders_placed        ON bar_orders (placed_at);
CREATE INDEX idx_bar_items_order          ON bar_order_items (order_id);
CREATE INDEX idx_bar_items_kitchen        ON bar_order_items (kitchen_status);
CREATE INDEX idx_enquiries_status         ON enquiries (status, assigned_to);
CREATE INDEX idx_enquiries_followup       ON enquiries (next_follow_up_at);
CREATE INDEX idx_enq_activities_enquiry   ON enquiry_activities (enquiry_id, occurred_at);
CREATE INDEX idx_invoices_member          ON invoices (member_id);
CREATE INDEX idx_invoices_client          ON invoices (business_client_id);
CREATE INDEX idx_invoices_date            ON invoices (issue_date);
CREATE INDEX idx_invoices_open            ON invoices (due_date);
CREATE INDEX idx_invoice_items_invoice    ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_source     ON invoice_items (source);
CREATE INDEX idx_payments_invoice         ON payments (invoice_id);
CREATE INDEX idx_payments_paid_at         ON payments (paid_at);
CREATE INDEX idx_expenses_status          ON expenses (status, due_date);
CREATE INDEX idx_shifts_start             ON shifts (starts_at);
CREATE INDEX idx_attendance_employee      ON attendance_records (employee_id, clock_in);
CREATE INDEX idx_leave_employee           ON leave_requests (employee_id, status);
CREATE INDEX idx_payroll_items_employee   ON payroll_items (employee_id);
CREATE INDEX idx_notifications_user       ON notifications (recipient_user_id, is_read);
CREATE INDEX idx_notifications_pending    ON notifications (scheduled_for);
CREATE INDEX idx_audit_entity             ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_user               ON audit_logs (user_id, created_at DESC);


-- =====================================================================================
