export const ROUTES = {
  HOME: '/',
  COURTS: '/courts',
  CAFE: '/cafe',
  SHOP: '/shop',
  MEMBERSHIPS: '/memberships',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RECEPTIONIST: '/frontdesk',
  MEMBER_PORTAL: '/member',
  MANAGER: '/manager',
  BAR: '/bar',
};
